// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Quizzer.Data;

namespace Quizzer.Data.Migrations
{
    [DbContext(typeof(QuizDbContext))]
    [Migration("20200610173518_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("IdentityServer4.EntityFramework.Entities.DeviceFlowCodes", b =>
                {
                    b.Property<string>("UserCode")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasMaxLength(50000);

                    b.Property<string>("DeviceCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<DateTime?>("Expiration")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("SubjectId")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.HasKey("UserCode");

                    b.HasIndex("DeviceCode")
                        .IsUnique();

                    b.HasIndex("Expiration");

                    b.ToTable("DeviceCodes");
                });

            modelBuilder.Entity("IdentityServer4.EntityFramework.Entities.PersistedGrant", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasMaxLength(50000);

                    b.Property<DateTime?>("Expiration")
                        .HasColumnType("datetime2");

                    b.Property<string>("SubjectId")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Key");

                    b.HasIndex("Expiration");

                    b.HasIndex("SubjectId", "ClientId", "Type");

                    b.ToTable("PersistedGrants");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Quizzer.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Quizzer.Models.Option", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("Options");

                    b.HasData(
                        new
                        {
                            Id = 11,
                            IsCorrect = true,
                            QuestionId = 1,
                            Text = "10 years in prison and a fine of $50,000"
                        },
                        new
                        {
                            Id = 12,
                            IsCorrect = false,
                            QuestionId = 1,
                            Text = "Fine of $5,000"
                        },
                        new
                        {
                            Id = 13,
                            IsCorrect = false,
                            QuestionId = 1,
                            Text = "Nothing"
                        },
                        new
                        {
                            Id = 14,
                            IsCorrect = false,
                            QuestionId = 1,
                            Text = "15 years in prison and a fine of $10,000"
                        },
                        new
                        {
                            Id = 21,
                            IsCorrect = true,
                            QuestionId = 2,
                            Text = "Gearbox Software"
                        },
                        new
                        {
                            Id = 22,
                            IsCorrect = false,
                            QuestionId = 2,
                            Text = "2K Games"
                        },
                        new
                        {
                            Id = 23,
                            IsCorrect = false,
                            QuestionId = 2,
                            Text = "Activision"
                        },
                        new
                        {
                            Id = 24,
                            IsCorrect = false,
                            QuestionId = 2,
                            Text = "Rockstar Games"
                        },
                        new
                        {
                            Id = 31,
                            IsCorrect = true,
                            QuestionId = 3,
                            Text = "Six"
                        },
                        new
                        {
                            Id = 32,
                            IsCorrect = false,
                            QuestionId = 3,
                            Text = "Seven"
                        },
                        new
                        {
                            Id = 33,
                            IsCorrect = false,
                            QuestionId = 3,
                            Text = "Five"
                        },
                        new
                        {
                            Id = 34,
                            IsCorrect = false,
                            QuestionId = 3,
                            Text = "Eight"
                        },
                        new
                        {
                            Id = 41,
                            IsCorrect = true,
                            QuestionId = 4,
                            Text = "Marie"
                        },
                        new
                        {
                            Id = 42,
                            IsCorrect = false,
                            QuestionId = 4,
                            Text = "Cyrus"
                        },
                        new
                        {
                            Id = 43,
                            IsCorrect = false,
                            QuestionId = 4,
                            Text = "Palutena"
                        },
                        new
                        {
                            Id = 44,
                            IsCorrect = false,
                            QuestionId = 4,
                            Text = "Shulk"
                        },
                        new
                        {
                            Id = 51,
                            IsCorrect = true,
                            QuestionId = 5,
                            Text = "7"
                        },
                        new
                        {
                            Id = 52,
                            IsCorrect = false,
                            QuestionId = 5,
                            Text = "5"
                        },
                        new
                        {
                            Id = 53,
                            IsCorrect = false,
                            QuestionId = 5,
                            Text = "10"
                        },
                        new
                        {
                            Id = 54,
                            IsCorrect = false,
                            QuestionId = 5,
                            Text = "12"
                        },
                        new
                        {
                            Id = 61,
                            IsCorrect = true,
                            QuestionId = 6,
                            Text = "Final Fantasy Versus XIII"
                        },
                        new
                        {
                            Id = 62,
                            IsCorrect = false,
                            QuestionId = 6,
                            Text = "Final Fantasy: Reborn"
                        },
                        new
                        {
                            Id = 63,
                            IsCorrect = false,
                            QuestionId = 6,
                            Text = "Final Fantasy XVI"
                        },
                        new
                        {
                            Id = 64,
                            IsCorrect = false,
                            QuestionId = 6,
                            Text = "Final Fantasy XIII-3"
                        },
                        new
                        {
                            Id = 71,
                            IsCorrect = true,
                            QuestionId = 7,
                            Text = "A potato"
                        },
                        new
                        {
                            Id = 72,
                            IsCorrect = false,
                            QuestionId = 7,
                            Text = "A tomato"
                        },
                        new
                        {
                            Id = 73,
                            IsCorrect = false,
                            QuestionId = 7,
                            Text = "A lemon"
                        },
                        new
                        {
                            Id = 74,
                            IsCorrect = false,
                            QuestionId = 7,
                            Text = "An apple"
                        },
                        new
                        {
                            Id = 81,
                            IsCorrect = true,
                            QuestionId = 8,
                            Text = "Ron Jeremy"
                        },
                        new
                        {
                            Id = 82,
                            IsCorrect = false,
                            QuestionId = 8,
                            Text = "Sasha Grey"
                        },
                        new
                        {
                            Id = 83,
                            IsCorrect = false,
                            QuestionId = 8,
                            Text = "Burt Reynolds"
                        },
                        new
                        {
                            Id = 84,
                            IsCorrect = false,
                            QuestionId = 8,
                            Text = "Hulk Hogan"
                        },
                        new
                        {
                            Id = 91,
                            IsCorrect = true,
                            QuestionId = 9,
                            Text = "50 Blessings"
                        },
                        new
                        {
                            Id = 92,
                            IsCorrect = false,
                            QuestionId = 9,
                            Text = "American Blessings"
                        },
                        new
                        {
                            Id = 93,
                            IsCorrect = false,
                            QuestionId = 9,
                            Text = "50 Saints"
                        },
                        new
                        {
                            Id = 94,
                            IsCorrect = false,
                            QuestionId = 9,
                            Text = "USSR's Blessings"
                        },
                        new
                        {
                            Id = 101,
                            IsCorrect = true,
                            QuestionId = 10,
                            Text = "2, 3, 1"
                        },
                        new
                        {
                            Id = 102,
                            IsCorrect = false,
                            QuestionId = 10,
                            Text = "1, 2, 3"
                        },
                        new
                        {
                            Id = 103,
                            IsCorrect = false,
                            QuestionId = 10,
                            Text = "1, 3, 2"
                        },
                        new
                        {
                            Id = 104,
                            IsCorrect = false,
                            QuestionId = 10,
                            Text = "2, 1, 3"
                        },
                        new
                        {
                            Id = 111,
                            IsCorrect = true,
                            QuestionId = 11,
                            Text = "Pokémon Crystal"
                        },
                        new
                        {
                            Id = 112,
                            IsCorrect = false,
                            QuestionId = 11,
                            Text = "Pokémon Platinum"
                        },
                        new
                        {
                            Id = 113,
                            IsCorrect = false,
                            QuestionId = 11,
                            Text = "Pokémon FireRed"
                        },
                        new
                        {
                            Id = 114,
                            IsCorrect = false,
                            QuestionId = 11,
                            Text = "Pokémon Black"
                        },
                        new
                        {
                            Id = 121,
                            IsCorrect = true,
                            QuestionId = 12,
                            Text = "Aperture Fixtures"
                        },
                        new
                        {
                            Id = 122,
                            IsCorrect = false,
                            QuestionId = 12,
                            Text = "Aperture Lavatories"
                        },
                        new
                        {
                            Id = 123,
                            IsCorrect = false,
                            QuestionId = 12,
                            Text = "Aperture Science Innovators"
                        },
                        new
                        {
                            Id = 124,
                            IsCorrect = false,
                            QuestionId = 12,
                            Text = "Wheatley Laboratories"
                        },
                        new
                        {
                            Id = 131,
                            IsCorrect = true,
                            QuestionId = 13,
                            Text = "Mario Party 4"
                        },
                        new
                        {
                            Id = 132,
                            IsCorrect = false,
                            QuestionId = 13,
                            Text = "New Super Mario Bros."
                        },
                        new
                        {
                            Id = 133,
                            IsCorrect = false,
                            QuestionId = 13,
                            Text = "Mario Kart Wii"
                        },
                        new
                        {
                            Id = 134,
                            IsCorrect = false,
                            QuestionId = 13,
                            Text = "Super Mario 3D World"
                        },
                        new
                        {
                            Id = 141,
                            IsCorrect = true,
                            QuestionId = 14,
                            Text = "Alexandros Mograine"
                        },
                        new
                        {
                            Id = 142,
                            IsCorrect = false,
                            QuestionId = 14,
                            Text = "Tirion Fordring"
                        },
                        new
                        {
                            Id = 143,
                            IsCorrect = false,
                            QuestionId = 14,
                            Text = "Arthas Menethil"
                        },
                        new
                        {
                            Id = 144,
                            IsCorrect = false,
                            QuestionId = 14,
                            Text = "Uther the Lightbringer"
                        },
                        new
                        {
                            Id = 151,
                            IsCorrect = true,
                            QuestionId = 15,
                            Text = "Huzzah!"
                        },
                        new
                        {
                            Id = 152,
                            IsCorrect = false,
                            QuestionId = 15,
                            Text = "Yes!"
                        },
                        new
                        {
                            Id = 153,
                            IsCorrect = false,
                            QuestionId = 15,
                            Text = "Whoa there!"
                        },
                        new
                        {
                            Id = 154,
                            IsCorrect = false,
                            QuestionId = 15,
                            Text = "Nyeh heh heh!"
                        },
                        new
                        {
                            Id = 161,
                            IsCorrect = true,
                            QuestionId = 16,
                            Text = "Lucas"
                        },
                        new
                        {
                            Id = 162,
                            IsCorrect = false,
                            QuestionId = 16,
                            Text = "Mega Man"
                        },
                        new
                        {
                            Id = 163,
                            IsCorrect = false,
                            QuestionId = 16,
                            Text = "Meta Knight"
                        },
                        new
                        {
                            Id = 164,
                            IsCorrect = false,
                            QuestionId = 16,
                            Text = "Diddy Kong"
                        },
                        new
                        {
                            Id = 171,
                            IsCorrect = true,
                            QuestionId = 17,
                            Text = "ZUN"
                        },
                        new
                        {
                            Id = 172,
                            IsCorrect = false,
                            QuestionId = 17,
                            Text = "SUN"
                        },
                        new
                        {
                            Id = 173,
                            IsCorrect = false,
                            QuestionId = 17,
                            Text = "RUN"
                        },
                        new
                        {
                            Id = 174,
                            IsCorrect = false,
                            QuestionId = 17,
                            Text = "PUN"
                        },
                        new
                        {
                            Id = 181,
                            IsCorrect = true,
                            QuestionId = 18,
                            Text = "Victor Branco"
                        },
                        new
                        {
                            Id = 182,
                            IsCorrect = false,
                            QuestionId = 18,
                            Text = "&Aacute;lvaro Neves"
                        },
                        new
                        {
                            Id = 183,
                            IsCorrect = false,
                            QuestionId = 18,
                            Text = "Armando Becker"
                        },
                        new
                        {
                            Id = 184,
                            IsCorrect = false,
                            QuestionId = 18,
                            Text = "Milo Rego"
                        },
                        new
                        {
                            Id = 191,
                            IsCorrect = true,
                            QuestionId = 19,
                            Text = "Pie"
                        },
                        new
                        {
                            Id = 192,
                            IsCorrect = false,
                            QuestionId = 19,
                            Text = "Shish Kabob"
                        },
                        new
                        {
                            Id = 193,
                            IsCorrect = false,
                            QuestionId = 19,
                            Text = "Hamburger"
                        },
                        new
                        {
                            Id = 194,
                            IsCorrect = false,
                            QuestionId = 19,
                            Text = "Lasagna"
                        },
                        new
                        {
                            Id = 201,
                            IsCorrect = true,
                            QuestionId = 20,
                            Text = "U.N. Owen Was Her"
                        },
                        new
                        {
                            Id = 202,
                            IsCorrect = false,
                            QuestionId = 20,
                            Text = "Septette for the Dead Princess"
                        },
                        new
                        {
                            Id = 203,
                            IsCorrect = false,
                            QuestionId = 20,
                            Text = "Flowering Night"
                        },
                        new
                        {
                            Id = 204,
                            IsCorrect = false,
                            QuestionId = 20,
                            Text = "Pierrot of the Star-Spangled Banner"
                        },
                        new
                        {
                            Id = 211,
                            IsCorrect = true,
                            QuestionId = 21,
                            Text = "The Thing"
                        },
                        new
                        {
                            Id = 212,
                            IsCorrect = false,
                            QuestionId = 21,
                            Text = "The Evil Dead"
                        },
                        new
                        {
                            Id = 213,
                            IsCorrect = false,
                            QuestionId = 21,
                            Text = "Saw"
                        },
                        new
                        {
                            Id = 214,
                            IsCorrect = false,
                            QuestionId = 21,
                            Text = "Alien"
                        },
                        new
                        {
                            Id = 221,
                            IsCorrect = true,
                            QuestionId = 22,
                            Text = "November 29th, 2016"
                        },
                        new
                        {
                            Id = 222,
                            IsCorrect = false,
                            QuestionId = 22,
                            Text = "October 25th, 2016"
                        },
                        new
                        {
                            Id = 223,
                            IsCorrect = false,
                            QuestionId = 22,
                            Text = "December 31th, 2016"
                        },
                        new
                        {
                            Id = 224,
                            IsCorrect = false,
                            QuestionId = 22,
                            Text = "November 30th, 2016"
                        },
                        new
                        {
                            Id = 231,
                            IsCorrect = true,
                            QuestionId = 23,
                            Text = "The Hotshot"
                        },
                        new
                        {
                            Id = 232,
                            IsCorrect = false,
                            QuestionId = 23,
                            Text = "The Discard"
                        },
                        new
                        {
                            Id = 233,
                            IsCorrect = false,
                            QuestionId = 23,
                            Text = "The Elephant"
                        },
                        new
                        {
                            Id = 234,
                            IsCorrect = false,
                            QuestionId = 23,
                            Text = "The Mohawk"
                        },
                        new
                        {
                            Id = 241,
                            IsCorrect = true,
                            QuestionId = 24,
                            Text = "Yu Narukami"
                        },
                        new
                        {
                            Id = 242,
                            IsCorrect = false,
                            QuestionId = 24,
                            Text = "Chino Mashido"
                        },
                        new
                        {
                            Id = 243,
                            IsCorrect = false,
                            QuestionId = 24,
                            Text = "Tunki Sunada"
                        },
                        new
                        {
                            Id = 244,
                            IsCorrect = false,
                            QuestionId = 24,
                            Text = "Masaki Narinaka"
                        },
                        new
                        {
                            Id = 251,
                            IsCorrect = true,
                            QuestionId = 25,
                            Text = "Luminid"
                        },
                        new
                        {
                            Id = 252,
                            IsCorrect = false,
                            QuestionId = 25,
                            Text = "Dragalge"
                        },
                        new
                        {
                            Id = 253,
                            IsCorrect = false,
                            QuestionId = 25,
                            Text = "Mandibuzz"
                        },
                        new
                        {
                            Id = 254,
                            IsCorrect = false,
                            QuestionId = 25,
                            Text = "Araquanid"
                        },
                        new
                        {
                            Id = 261,
                            IsCorrect = true,
                            QuestionId = 26,
                            Text = "Truffle Worm"
                        },
                        new
                        {
                            Id = 262,
                            IsCorrect = false,
                            QuestionId = 26,
                            Text = "Suspicious Looking Fish"
                        },
                        new
                        {
                            Id = 263,
                            IsCorrect = false,
                            QuestionId = 26,
                            Text = "King Grasshopper"
                        },
                        new
                        {
                            Id = 264,
                            IsCorrect = false,
                            QuestionId = 26,
                            Text = "Slug"
                        },
                        new
                        {
                            Id = 271,
                            IsCorrect = true,
                            QuestionId = 27,
                            Text = "2011"
                        },
                        new
                        {
                            Id = 272,
                            IsCorrect = false,
                            QuestionId = 27,
                            Text = "2010"
                        },
                        new
                        {
                            Id = 273,
                            IsCorrect = false,
                            QuestionId = 27,
                            Text = "2008"
                        },
                        new
                        {
                            Id = 274,
                            IsCorrect = false,
                            QuestionId = 27,
                            Text = "2009"
                        },
                        new
                        {
                            Id = 281,
                            IsCorrect = true,
                            QuestionId = 28,
                            Text = "Sniper"
                        },
                        new
                        {
                            Id = 282,
                            IsCorrect = false,
                            QuestionId = 28,
                            Text = "Heavy"
                        },
                        new
                        {
                            Id = 283,
                            IsCorrect = false,
                            QuestionId = 28,
                            Text = "Soldier"
                        },
                        new
                        {
                            Id = 284,
                            IsCorrect = false,
                            QuestionId = 28,
                            Text = "Scout"
                        },
                        new
                        {
                            Id = 291,
                            IsCorrect = true,
                            QuestionId = 29,
                            Text = "Dimitri Lousteau"
                        },
                        new
                        {
                            Id = 292,
                            IsCorrect = false,
                            QuestionId = 29,
                            Text = "Mz. Ruby"
                        },
                        new
                        {
                            Id = 293,
                            IsCorrect = false,
                            QuestionId = 29,
                            Text = "Muggshot"
                        },
                        new
                        {
                            Id = 294,
                            IsCorrect = false,
                            QuestionId = 29,
                            Text = "Clockwerk"
                        },
                        new
                        {
                            Id = 301,
                            IsCorrect = true,
                            QuestionId = 30,
                            Text = "The Gage Weapon Pack #1"
                        },
                        new
                        {
                            Id = 302,
                            IsCorrect = false,
                            QuestionId = 30,
                            Text = "The Overkill Pack"
                        },
                        new
                        {
                            Id = 303,
                            IsCorrect = false,
                            QuestionId = 30,
                            Text = "The Gage Chivalry Pack"
                        },
                        new
                        {
                            Id = 304,
                            IsCorrect = false,
                            QuestionId = 30,
                            Text = "The Gage Historical Pack"
                        },
                        new
                        {
                            Id = 311,
                            IsCorrect = true,
                            QuestionId = 31,
                            Text = "The Sound of Crickets"
                        },
                        new
                        {
                            Id = 312,
                            IsCorrect = false,
                            QuestionId = 31,
                            Text = "Attacks from Koopas"
                        },
                        new
                        {
                            Id = 313,
                            IsCorrect = false,
                            QuestionId = 31,
                            Text = "The \"Ice Storm\" Item"
                        },
                        new
                        {
                            Id = 314,
                            IsCorrect = false,
                            QuestionId = 31,
                            Text = "The Hammer"
                        },
                        new
                        {
                            Id = 321,
                            IsCorrect = true,
                            QuestionId = 32,
                            Text = "$0 USD"
                        },
                        new
                        {
                            Id = 322,
                            IsCorrect = false,
                            QuestionId = 32,
                            Text = "$5 USD"
                        },
                        new
                        {
                            Id = 323,
                            IsCorrect = false,
                            QuestionId = 32,
                            Text = "$10 USD"
                        },
                        new
                        {
                            Id = 324,
                            IsCorrect = false,
                            QuestionId = 32,
                            Text = "$15 USD"
                        },
                        new
                        {
                            Id = 331,
                            IsCorrect = true,
                            QuestionId = 33,
                            Text = "Call Of Duty: Black Ops III"
                        },
                        new
                        {
                            Id = 332,
                            IsCorrect = false,
                            QuestionId = 33,
                            Text = "Call Of Duty: Black Ops"
                        },
                        new
                        {
                            Id = 333,
                            IsCorrect = false,
                            QuestionId = 33,
                            Text = "Call Of Duty: World At War"
                        },
                        new
                        {
                            Id = 334,
                            IsCorrect = false,
                            QuestionId = 33,
                            Text = "Call Of Duty: Black Ops II"
                        },
                        new
                        {
                            Id = 341,
                            IsCorrect = true,
                            QuestionId = 34,
                            Text = "4"
                        },
                        new
                        {
                            Id = 342,
                            IsCorrect = false,
                            QuestionId = 34,
                            Text = "7"
                        },
                        new
                        {
                            Id = 343,
                            IsCorrect = false,
                            QuestionId = 34,
                            Text = "5"
                        },
                        new
                        {
                            Id = 344,
                            IsCorrect = false,
                            QuestionId = 34,
                            Text = "3"
                        },
                        new
                        {
                            Id = 351,
                            IsCorrect = true,
                            QuestionId = 35,
                            Text = "Eric Barone"
                        },
                        new
                        {
                            Id = 352,
                            IsCorrect = false,
                            QuestionId = 35,
                            Text = "Daisuke Amaya"
                        },
                        new
                        {
                            Id = 353,
                            IsCorrect = false,
                            QuestionId = 35,
                            Text = "Jasper Byrne"
                        },
                        new
                        {
                            Id = 354,
                            IsCorrect = false,
                            QuestionId = 35,
                            Text = "Lucas Pope"
                        },
                        new
                        {
                            Id = 361,
                            IsCorrect = true,
                            QuestionId = 36,
                            Text = "Monkeys"
                        },
                        new
                        {
                            Id = 362,
                            IsCorrect = false,
                            QuestionId = 36,
                            Text = "Alligators"
                        },
                        new
                        {
                            Id = 363,
                            IsCorrect = false,
                            QuestionId = 36,
                            Text = "Pigeons"
                        },
                        new
                        {
                            Id = 364,
                            IsCorrect = false,
                            QuestionId = 36,
                            Text = "Lizards"
                        },
                        new
                        {
                            Id = 371,
                            IsCorrect = true,
                            QuestionId = 37,
                            Text = "Group 935"
                        },
                        new
                        {
                            Id = 372,
                            IsCorrect = false,
                            QuestionId = 37,
                            Text = "Group Reanimate"
                        },
                        new
                        {
                            Id = 373,
                            IsCorrect = false,
                            QuestionId = 37,
                            Text = "Group Rezurrection"
                        },
                        new
                        {
                            Id = 374,
                            IsCorrect = false,
                            QuestionId = 37,
                            Text = "Division 9"
                        },
                        new
                        {
                            Id = 381,
                            IsCorrect = true,
                            QuestionId = 38,
                            Text = "2006"
                        },
                        new
                        {
                            Id = 382,
                            IsCorrect = false,
                            QuestionId = 38,
                            Text = "2009"
                        },
                        new
                        {
                            Id = 383,
                            IsCorrect = false,
                            QuestionId = 38,
                            Text = "2007"
                        },
                        new
                        {
                            Id = 384,
                            IsCorrect = false,
                            QuestionId = 38,
                            Text = "2008"
                        },
                        new
                        {
                            Id = 391,
                            IsCorrect = true,
                            QuestionId = 39,
                            Text = "Ed"
                        },
                        new
                        {
                            Id = 392,
                            IsCorrect = false,
                            QuestionId = 39,
                            Text = "Charles"
                        },
                        new
                        {
                            Id = 393,
                            IsCorrect = false,
                            QuestionId = 39,
                            Text = "Lee"
                        },
                        new
                        {
                            Id = 394,
                            IsCorrect = false,
                            QuestionId = 39,
                            Text = "Walter"
                        },
                        new
                        {
                            Id = 401,
                            IsCorrect = true,
                            QuestionId = 40,
                            Text = "September 17, 2013"
                        },
                        new
                        {
                            Id = 402,
                            IsCorrect = false,
                            QuestionId = 40,
                            Text = "August 17, 2013"
                        },
                        new
                        {
                            Id = 403,
                            IsCorrect = false,
                            QuestionId = 40,
                            Text = "April 14, 2015"
                        },
                        new
                        {
                            Id = 404,
                            IsCorrect = false,
                            QuestionId = 40,
                            Text = "November 18, 2014"
                        },
                        new
                        {
                            Id = 411,
                            IsCorrect = true,
                            QuestionId = 41,
                            Text = "Illumise"
                        },
                        new
                        {
                            Id = 412,
                            IsCorrect = false,
                            QuestionId = 41,
                            Text = "Infernape"
                        },
                        new
                        {
                            Id = 413,
                            IsCorrect = false,
                            QuestionId = 41,
                            Text = "Ivysaur"
                        },
                        new
                        {
                            Id = 414,
                            IsCorrect = false,
                            QuestionId = 41,
                            Text = "Igglybuff"
                        },
                        new
                        {
                            Id = 421,
                            IsCorrect = true,
                            QuestionId = 42,
                            Text = "No Mercy"
                        },
                        new
                        {
                            Id = 422,
                            IsCorrect = false,
                            QuestionId = 42,
                            Text = "Subway Sprint"
                        },
                        new
                        {
                            Id = 423,
                            IsCorrect = false,
                            QuestionId = 42,
                            Text = "Hospital Havoc"
                        },
                        new
                        {
                            Id = 424,
                            IsCorrect = false,
                            QuestionId = 42,
                            Text = "Blood Harvest"
                        },
                        new
                        {
                            Id = 431,
                            IsCorrect = true,
                            QuestionId = 43,
                            Text = "Ripper Roo"
                        },
                        new
                        {
                            Id = 432,
                            IsCorrect = false,
                            QuestionId = 43,
                            Text = "Papu Papu"
                        },
                        new
                        {
                            Id = 433,
                            IsCorrect = false,
                            QuestionId = 43,
                            Text = "Komodo brothers"
                        },
                        new
                        {
                            Id = 434,
                            IsCorrect = false,
                            QuestionId = 43,
                            Text = "Nitros Oxide"
                        },
                        new
                        {
                            Id = 441,
                            IsCorrect = true,
                            QuestionId = 44,
                            Text = "Michael Cardenas"
                        },
                        new
                        {
                            Id = 442,
                            IsCorrect = false,
                            QuestionId = 44,
                            Text = "Packie McReary"
                        },
                        new
                        {
                            Id = 443,
                            IsCorrect = false,
                            QuestionId = 44,
                            Text = "Tommy Vercetti"
                        },
                        new
                        {
                            Id = 444,
                            IsCorrect = false,
                            QuestionId = 44,
                            Text = "Lester Crest"
                        },
                        new
                        {
                            Id = 451,
                            IsCorrect = true,
                            QuestionId = 45,
                            Text = "Destiny Islands"
                        },
                        new
                        {
                            Id = 452,
                            IsCorrect = false,
                            QuestionId = 45,
                            Text = "Agrabah"
                        },
                        new
                        {
                            Id = 453,
                            IsCorrect = false,
                            QuestionId = 45,
                            Text = "Land of Departure"
                        },
                        new
                        {
                            Id = 454,
                            IsCorrect = false,
                            QuestionId = 45,
                            Text = "Disney Town"
                        },
                        new
                        {
                            Id = 461,
                            IsCorrect = true,
                            QuestionId = 46,
                            Text = "Sosnovka"
                        },
                        new
                        {
                            Id = 462,
                            IsCorrect = false,
                            QuestionId = 46,
                            Text = "Novorepnoye"
                        },
                        new
                        {
                            Id = 463,
                            IsCorrect = false,
                            QuestionId = 46,
                            Text = "Mylta"
                        },
                        new
                        {
                            Id = 464,
                            IsCorrect = false,
                            QuestionId = 46,
                            Text = "Yasnaya"
                        },
                        new
                        {
                            Id = 471,
                            IsCorrect = true,
                            QuestionId = 47,
                            Text = "The Knight"
                        },
                        new
                        {
                            Id = 472,
                            IsCorrect = false,
                            QuestionId = 47,
                            Text = "The Wizard"
                        },
                        new
                        {
                            Id = 473,
                            IsCorrect = false,
                            QuestionId = 47,
                            Text = "The Archer"
                        },
                        new
                        {
                            Id = 474,
                            IsCorrect = false,
                            QuestionId = 47,
                            Text = "The Warrior"
                        },
                        new
                        {
                            Id = 481,
                            IsCorrect = true,
                            QuestionId = 48,
                            Text = "Sticks the Badger"
                        },
                        new
                        {
                            Id = 482,
                            IsCorrect = false,
                            QuestionId = 48,
                            Text = "Mighty the Armadillo"
                        },
                        new
                        {
                            Id = 483,
                            IsCorrect = false,
                            QuestionId = 48,
                            Text = "Espio the Chameleon"
                        },
                        new
                        {
                            Id = 484,
                            IsCorrect = false,
                            QuestionId = 48,
                            Text = "Rouge the Bat"
                        },
                        new
                        {
                            Id = 491,
                            IsCorrect = true,
                            QuestionId = 49,
                            Text = "Izayoi Sakuya"
                        },
                        new
                        {
                            Id = 492,
                            IsCorrect = false,
                            QuestionId = 49,
                            Text = "Hakurei Reimu"
                        },
                        new
                        {
                            Id = 493,
                            IsCorrect = false,
                            QuestionId = 49,
                            Text = "Kirisame Marisa"
                        },
                        new
                        {
                            Id = 494,
                            IsCorrect = false,
                            QuestionId = 49,
                            Text = "Kochiya Sanae"
                        },
                        new
                        {
                            Id = 501,
                            IsCorrect = true,
                            QuestionId = 50,
                            Text = "Pandora"
                        },
                        new
                        {
                            Id = 502,
                            IsCorrect = false,
                            QuestionId = 50,
                            Text = "Helios"
                        },
                        new
                        {
                            Id = 503,
                            IsCorrect = false,
                            QuestionId = 50,
                            Text = "Icarus"
                        },
                        new
                        {
                            Id = 504,
                            IsCorrect = false,
                            QuestionId = 50,
                            Text = "Orion"
                        });
                });

            modelBuilder.Entity("Quizzer.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Text = "What is the punishment for playing Postal 2 in New Zealand?"
                        },
                        new
                        {
                            Id = 2,
                            Text = "Which company developed the video game \"Borderlands\"?"
                        },
                        new
                        {
                            Id = 3,
                            Text = "How many Chaos Emeralds can you collect in the first Sonic The Hedgehog?"
                        },
                        new
                        {
                            Id = 4,
                            Text = "Which character is from \"Splatoon\"?"
                        },
                        new
                        {
                            Id = 5,
                            Text = "How many Star Spirits do you rescue in the Nintendo 64 video game \"Paper Mario\"?"
                        },
                        new
                        {
                            Id = 6,
                            Text = "What is the original name of Final Fantasy XV?"
                        },
                        new
                        {
                            Id = 7,
                            Text = "In Portal 2, the iconic character GLaDOS is turned into:"
                        },
                        new
                        {
                            Id = 8,
                            Text = "Which one of the following actors did not voice a character in \"Saints Row: The Third\"?"
                        },
                        new
                        {
                            Id = 9,
                            Text = "What was the name of the Secret Organization in the Hotline Miami series? "
                        },
                        new
                        {
                            Id = 10,
                            Text = "In which order do you need to hit some Deku Scrubs to open the first boss door in \"Ocarina of Time\"?"
                        },
                        new
                        {
                            Id = 11,
                            Text = "Which of the following Pokémon games released first?"
                        },
                        new
                        {
                            Id = 12,
                            Text = "In the Portal series, Aperture Science was founded under what name in the early 1940s?"
                        },
                        new
                        {
                            Id = 13,
                            Text = "In which Mario game did the Mega Mushroom make its debut?"
                        },
                        new
                        {
                            Id = 14,
                            Text = "In World of Warcraft lore, who was first to have the title \"The Ashbringer\"?"
                        },
                        new
                        {
                            Id = 15,
                            Text = "In the game \"Cave Story,\" what is the character Balrog's catchphrase?"
                        },
                        new
                        {
                            Id = 16,
                            Text = "Which of the following characters were considered for inclusion in Super Smash Bros. Melee?"
                        },
                        new
                        {
                            Id = 17,
                            Text = "The creator of the Touhou Project series is:"
                        },
                        new
                        {
                            Id = 18,
                            Text = "Who was the main antagonist of Max Payne 3 (2012)?"
                        },
                        new
                        {
                            Id = 19,
                            Text = "In Cook, Serve, Delicious!, which food is NOT included in the game?"
                        },
                        new
                        {
                            Id = 20,
                            Text = "In Touhou: Embodiment of Scarlet Devil, what song plays during Flandre Scarlet's boss fight?"
                        },
                        new
                        {
                            Id = 21,
                            Text = "Which horror movie had a sequel in the form of a video game released in August 20, 2002?"
                        },
                        new
                        {
                            Id = 22,
                            Text = "When was Final Fantasy XV released?"
                        },
                        new
                        {
                            Id = 23,
                            Text = "In WarioWare: Smooth Moves, which one of these is NOT a Form?"
                        },
                        new
                        {
                            Id = 24,
                            Text = "In the game \"Persona 4\", what is the canonical name of the protagonist?"
                        },
                        new
                        {
                            Id = 25,
                            Text = "Which of the following is not a real Pokémon?"
                        },
                        new
                        {
                            Id = 26,
                            Text = "What is the item required to summon the boss Duke Fishron in the game Terraria?"
                        },
                        new
                        {
                            Id = 27,
                            Text = "In what year were screenshots added to Steam?"
                        },
                        new
                        {
                            Id = 28,
                            Text = "Ellen McLain, the voice of GLaDOS in the Portal game series, is married to the voice actor for which Team Fortress 2 character?"
                        },
                        new
                        {
                            Id = 29,
                            Text = "Which one of these was not a member of the Fiendish Five in the game Sly Cooper and the Thievius Raccoonus?"
                        },
                        new
                        {
                            Id = 30,
                            Text = "What was the first weapon pack for \"PAYDAY 2\"?"
                        },
                        new
                        {
                            Id = 31,
                            Text = "In \"Paper Mario: The Thousand Year Door\", what is Hooktail's weakness?"
                        },
                        new
                        {
                            Id = 32,
                            Text = "How much did the indie game \"Cave Story\" cost when it was first released in 2004?"
                        },
                        new
                        {
                            Id = 33,
                            Text = "In which \"Call of Duty\" game are the \"Apothicons\" introduced in the Zombies mode?"
                        },
                        new
                        {
                            Id = 34,
                            Text = "In the \"Call Of Duty: Zombies\" map \"Origins\", how many steps are there to upgrade a Staff?"
                        },
                        new
                        {
                            Id = 35,
                            Text = "Who developed the 2016 farming RPG \"Stardew Valley\"?"
                        },
                        new
                        {
                            Id = 36,
                            Text = "What animal is featured in \"Bloons TD Battles\"?"
                        },
                        new
                        {
                            Id = 37,
                            Text = "In \"Call of Duty: Zombies\", what group does Doctor Maxis work for?"
                        },
                        new
                        {
                            Id = 38,
                            Text = "In what year was Pokémon Diamond &amp; Pearl released in Japan?"
                        },
                        new
                        {
                            Id = 39,
                            Text = "In Telltale Games' \"The Walking Dead: Season One\" what is the name of Clementine's father?"
                        },
                        new
                        {
                            Id = 40,
                            Text = "What was the original release date of Grand Theft Auto V?"
                        },
                        new
                        {
                            Id = 41,
                            Text = "What is the only Generation III Pokemon whose name begins with the letter I?"
                        },
                        new
                        {
                            Id = 42,
                            Text = "In Left 4 Dead, which campaign has the protagonists going through a subway in order to reach a hospital for evacuation?"
                        },
                        new
                        {
                            Id = 43,
                            Text = "Which of these characters is NOT a boss in Crash Bash?"
                        },
                        new
                        {
                            Id = 44,
                            Text = "What character is NOT apart of the Grand Theft Auto series?"
                        },
                        new
                        {
                            Id = 45,
                            Text = "In \"Kingdom Hearts\", what is the name of Sora's home world?"
                        },
                        new
                        {
                            Id = 46,
                            Text = "In \"PUBATTLEGROUNDS\" what is the name of the Military Base island?"
                        },
                        new
                        {
                            Id = 47,
                            Text = "In the MMO RPG \"Realm of the Mad God\", what class is known for having the highest possible defense?"
                        },
                        new
                        {
                            Id = 48,
                            Text = "Which one of these characters was first introduced in Sonic Boom: Rise of Lyric?"
                        },
                        new
                        {
                            Id = 49,
                            Text = "In Touhou 12: Undefined Fantastic Object, which of these was not a playable character?"
                        },
                        new
                        {
                            Id = 50,
                            Text = "In the 2000 video game \"Crimson Skies,\" what was the name of the protagonists' zeppelin?"
                        });
                });

            modelBuilder.Entity("Quizzer.Models.ScoreEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PlayerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ScoreEntries");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Quizzer.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Quizzer.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Quizzer.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Quizzer.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Quizzer.Models.Option", b =>
                {
                    b.HasOne("Quizzer.Models.Question", null)
                        .WithMany("Options")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
