// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Quizzer.Data;

namespace Quizzer.Data.Migrations
{
    [DbContext(typeof(QuizDbContext))]
    [Migration("20200607133117_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("IdentityServer4.EntityFramework.Entities.DeviceFlowCodes", b =>
                {
                    b.Property<string>("UserCode")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasMaxLength(50000);

                    b.Property<string>("DeviceCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<DateTime?>("Expiration")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("SubjectId")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.HasKey("UserCode");

                    b.HasIndex("DeviceCode")
                        .IsUnique();

                    b.HasIndex("Expiration");

                    b.ToTable("DeviceCodes");
                });

            modelBuilder.Entity("IdentityServer4.EntityFramework.Entities.PersistedGrant", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasMaxLength(50000);

                    b.Property<DateTime?>("Expiration")
                        .HasColumnType("datetime2");

                    b.Property<string>("SubjectId")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Key");

                    b.HasIndex("Expiration");

                    b.HasIndex("SubjectId", "ClientId", "Type");

                    b.ToTable("PersistedGrants");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Quizzer.Models.Answer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("Answers");

                    b.HasData(
                        new
                        {
                            Id = 11,
                            IsCorrect = true,
                            QuestionId = 1,
                            Text = "Labrador Retriever"
                        },
                        new
                        {
                            Id = 12,
                            IsCorrect = false,
                            QuestionId = 1,
                            Text = "Golden Retriever"
                        },
                        new
                        {
                            Id = 13,
                            IsCorrect = false,
                            QuestionId = 1,
                            Text = "Dalmatian"
                        },
                        new
                        {
                            Id = 14,
                            IsCorrect = false,
                            QuestionId = 1,
                            Text = "Shiba Inu"
                        },
                        new
                        {
                            Id = 21,
                            IsCorrect = true,
                            QuestionId = 2,
                            Text = "Scoobert"
                        },
                        new
                        {
                            Id = 22,
                            IsCorrect = false,
                            QuestionId = 2,
                            Text = "Scooter"
                        },
                        new
                        {
                            Id = 23,
                            IsCorrect = false,
                            QuestionId = 2,
                            Text = "Scrappy"
                        },
                        new
                        {
                            Id = 24,
                            IsCorrect = false,
                            QuestionId = 2,
                            Text = "Shooby"
                        },
                        new
                        {
                            Id = 31,
                            IsCorrect = true,
                            QuestionId = 3,
                            Text = "Badger"
                        },
                        new
                        {
                            Id = 32,
                            IsCorrect = false,
                            QuestionId = 3,
                            Text = "Fox"
                        },
                        new
                        {
                            Id = 33,
                            IsCorrect = false,
                            QuestionId = 3,
                            Text = "Frog"
                        },
                        new
                        {
                            Id = 34,
                            IsCorrect = false,
                            QuestionId = 3,
                            Text = "Rabbit"
                        },
                        new
                        {
                            Id = 41,
                            IsCorrect = true,
                            QuestionId = 4,
                            Text = "Keita Takahashi"
                        },
                        new
                        {
                            Id = 42,
                            IsCorrect = false,
                            QuestionId = 4,
                            Text = "Hideki Kamiya"
                        },
                        new
                        {
                            Id = 43,
                            IsCorrect = false,
                            QuestionId = 4,
                            Text = "Shu Takumi"
                        },
                        new
                        {
                            Id = 44,
                            IsCorrect = false,
                            QuestionId = 4,
                            Text = "Shinji Mikami"
                        },
                        new
                        {
                            Id = 51,
                            IsCorrect = true,
                            QuestionId = 5,
                            Text = "Jones"
                        },
                        new
                        {
                            Id = 52,
                            IsCorrect = false,
                            QuestionId = 5,
                            Text = "Williams"
                        },
                        new
                        {
                            Id = 53,
                            IsCorrect = false,
                            QuestionId = 5,
                            Text = "Davies"
                        },
                        new
                        {
                            Id = 54,
                            IsCorrect = false,
                            QuestionId = 5,
                            Text = "Evans"
                        },
                        new
                        {
                            Id = 61,
                            IsCorrect = true,
                            QuestionId = 6,
                            Text = "Amazon"
                        },
                        new
                        {
                            Id = 62,
                            IsCorrect = false,
                            QuestionId = 6,
                            Text = "eBay"
                        },
                        new
                        {
                            Id = 63,
                            IsCorrect = false,
                            QuestionId = 6,
                            Text = "Overstock"
                        },
                        new
                        {
                            Id = 64,
                            IsCorrect = false,
                            QuestionId = 6,
                            Text = "Shopify"
                        },
                        new
                        {
                            Id = 71,
                            IsCorrect = true,
                            QuestionId = 7,
                            Text = "Leicester City"
                        },
                        new
                        {
                            Id = 72,
                            IsCorrect = false,
                            QuestionId = 7,
                            Text = "Northampton Town"
                        },
                        new
                        {
                            Id = 73,
                            IsCorrect = false,
                            QuestionId = 7,
                            Text = "Bradford City"
                        },
                        new
                        {
                            Id = 74,
                            IsCorrect = false,
                            QuestionId = 7,
                            Text = "West Bromwich Albion"
                        },
                        new
                        {
                            Id = 81,
                            IsCorrect = true,
                            QuestionId = 8,
                            Text = "Metamorphic"
                        },
                        new
                        {
                            Id = 82,
                            IsCorrect = false,
                            QuestionId = 8,
                            Text = "Sedimentary"
                        },
                        new
                        {
                            Id = 83,
                            IsCorrect = false,
                            QuestionId = 8,
                            Text = "Igneous"
                        },
                        new
                        {
                            Id = 84,
                            IsCorrect = false,
                            QuestionId = 8,
                            Text = "Diamond"
                        },
                        new
                        {
                            Id = 91,
                            IsCorrect = true,
                            QuestionId = 9,
                            Text = "Gigahertz"
                        },
                        new
                        {
                            Id = 92,
                            IsCorrect = false,
                            QuestionId = 9,
                            Text = "Gigahotz"
                        },
                        new
                        {
                            Id = 93,
                            IsCorrect = false,
                            QuestionId = 9,
                            Text = "Gigahetz"
                        },
                        new
                        {
                            Id = 94,
                            IsCorrect = false,
                            QuestionId = 9,
                            Text = "Gigahatz"
                        },
                        new
                        {
                            Id = 101,
                            IsCorrect = true,
                            QuestionId = 10,
                            Text = "2000"
                        },
                        new
                        {
                            Id = 102,
                            IsCorrect = false,
                            QuestionId = 10,
                            Text = "1998"
                        },
                        new
                        {
                            Id = 103,
                            IsCorrect = false,
                            QuestionId = 10,
                            Text = "1999"
                        },
                        new
                        {
                            Id = 104,
                            IsCorrect = false,
                            QuestionId = 10,
                            Text = "2001"
                        },
                        new
                        {
                            Id = 111,
                            IsCorrect = true,
                            QuestionId = 11,
                            Text = "Africa"
                        },
                        new
                        {
                            Id = 112,
                            IsCorrect = false,
                            QuestionId = 11,
                            Text = "South America"
                        },
                        new
                        {
                            Id = 113,
                            IsCorrect = false,
                            QuestionId = 11,
                            Text = "Europe"
                        },
                        new
                        {
                            Id = 114,
                            IsCorrect = false,
                            QuestionId = 11,
                            Text = "Asia"
                        },
                        new
                        {
                            Id = 121,
                            IsCorrect = true,
                            QuestionId = 12,
                            Text = "The Chemical Brothers"
                        },
                        new
                        {
                            Id = 122,
                            IsCorrect = false,
                            QuestionId = 12,
                            Text = "Air"
                        },
                        new
                        {
                            Id = 123,
                            IsCorrect = false,
                            QuestionId = 12,
                            Text = "Justice"
                        },
                        new
                        {
                            Id = 124,
                            IsCorrect = false,
                            QuestionId = 12,
                            Text = "Daft Punk"
                        },
                        new
                        {
                            Id = 131,
                            IsCorrect = true,
                            QuestionId = 13,
                            Text = "Invoker"
                        },
                        new
                        {
                            Id = 132,
                            IsCorrect = false,
                            QuestionId = 13,
                            Text = "Mercy"
                        },
                        new
                        {
                            Id = 133,
                            IsCorrect = false,
                            QuestionId = 13,
                            Text = "Winston"
                        },
                        new
                        {
                            Id = 134,
                            IsCorrect = false,
                            QuestionId = 13,
                            Text = "Zenyatta"
                        },
                        new
                        {
                            Id = 141,
                            IsCorrect = true,
                            QuestionId = 14,
                            Text = "All Dogs Go To Heaven"
                        },
                        new
                        {
                            Id = 142,
                            IsCorrect = false,
                            QuestionId = 14,
                            Text = "Titan A.E."
                        },
                        new
                        {
                            Id = 143,
                            IsCorrect = false,
                            QuestionId = 14,
                            Text = "Anastasia"
                        },
                        new
                        {
                            Id = 144,
                            IsCorrect = false,
                            QuestionId = 14,
                            Text = "The Land Before Time"
                        },
                        new
                        {
                            Id = 151,
                            IsCorrect = true,
                            QuestionId = 15,
                            Text = "Qatar"
                        },
                        new
                        {
                            Id = 152,
                            IsCorrect = false,
                            QuestionId = 15,
                            Text = "Kuwait"
                        },
                        new
                        {
                            Id = 153,
                            IsCorrect = false,
                            QuestionId = 15,
                            Text = "United Arab Emirates"
                        },
                        new
                        {
                            Id = 154,
                            IsCorrect = false,
                            QuestionId = 15,
                            Text = "Jordan"
                        },
                        new
                        {
                            Id = 161,
                            IsCorrect = true,
                            QuestionId = 16,
                            Text = "Head"
                        },
                        new
                        {
                            Id = 162,
                            IsCorrect = false,
                            QuestionId = 16,
                            Text = "Arm"
                        },
                        new
                        {
                            Id = 163,
                            IsCorrect = false,
                            QuestionId = 16,
                            Text = "Leg"
                        },
                        new
                        {
                            Id = 164,
                            IsCorrect = false,
                            QuestionId = 16,
                            Text = "Chest"
                        },
                        new
                        {
                            Id = 171,
                            IsCorrect = true,
                            QuestionId = 17,
                            Text = "The Elves"
                        },
                        new
                        {
                            Id = 172,
                            IsCorrect = false,
                            QuestionId = 17,
                            Text = "Wicked"
                        },
                        new
                        {
                            Id = 173,
                            IsCorrect = false,
                            QuestionId = 17,
                            Text = "Hamilton"
                        },
                        new
                        {
                            Id = 174,
                            IsCorrect = false,
                            QuestionId = 17,
                            Text = "The Book of Mormon"
                        },
                        new
                        {
                            Id = 181,
                            IsCorrect = true,
                            QuestionId = 18,
                            Text = "Link"
                        },
                        new
                        {
                            Id = 182,
                            IsCorrect = false,
                            QuestionId = 18,
                            Text = "Wario"
                        },
                        new
                        {
                            Id = 183,
                            IsCorrect = false,
                            QuestionId = 18,
                            Text = "Q*bert"
                        },
                        new
                        {
                            Id = 184,
                            IsCorrect = false,
                            QuestionId = 18,
                            Text = "Solid Snake"
                        },
                        new
                        {
                            Id = 191,
                            IsCorrect = true,
                            QuestionId = 19,
                            Text = "The Shining"
                        },
                        new
                        {
                            Id = 192,
                            IsCorrect = false,
                            QuestionId = 19,
                            Text = "2001: A Space Odyssey"
                        },
                        new
                        {
                            Id = 193,
                            IsCorrect = false,
                            QuestionId = 19,
                            Text = " Dr. Strangelove "
                        },
                        new
                        {
                            Id = 194,
                            IsCorrect = false,
                            QuestionId = 19,
                            Text = "Eyes Wide Shut"
                        },
                        new
                        {
                            Id = 201,
                            IsCorrect = true,
                            QuestionId = 20,
                            Text = "Duran Duran"
                        },
                        new
                        {
                            Id = 202,
                            IsCorrect = false,
                            QuestionId = 20,
                            Text = "The Cure"
                        },
                        new
                        {
                            Id = 203,
                            IsCorrect = false,
                            QuestionId = 20,
                            Text = "New Order"
                        },
                        new
                        {
                            Id = 204,
                            IsCorrect = false,
                            QuestionId = 20,
                            Text = "Depeche Mode"
                        },
                        new
                        {
                            Id = 211,
                            IsCorrect = true,
                            QuestionId = 21,
                            Text = "Matthew \"Rickety Cricket\" Mara"
                        },
                        new
                        {
                            Id = 212,
                            IsCorrect = false,
                            QuestionId = 21,
                            Text = "Colin the Thief"
                        },
                        new
                        {
                            Id = 213,
                            IsCorrect = false,
                            QuestionId = 21,
                            Text = "Ben the Soldier"
                        },
                        new
                        {
                            Id = 214,
                            IsCorrect = false,
                            QuestionId = 21,
                            Text = "Kevin Gallagher aka Lil' Kevin"
                        },
                        new
                        {
                            Id = 221,
                            IsCorrect = true,
                            QuestionId = 22,
                            Text = "Tuba"
                        },
                        new
                        {
                            Id = 222,
                            IsCorrect = false,
                            QuestionId = 22,
                            Text = "Trombone"
                        },
                        new
                        {
                            Id = 223,
                            IsCorrect = false,
                            QuestionId = 22,
                            Text = "Contrabass"
                        },
                        new
                        {
                            Id = 224,
                            IsCorrect = false,
                            QuestionId = 22,
                            Text = "Bassoon"
                        },
                        new
                        {
                            Id = 231,
                            IsCorrect = true,
                            QuestionId = 23,
                            Text = "Distant Drums"
                        },
                        new
                        {
                            Id = 232,
                            IsCorrect = false,
                            QuestionId = 23,
                            Text = "Treasure of the Sierra Madre"
                        },
                        new
                        {
                            Id = 233,
                            IsCorrect = false,
                            QuestionId = 23,
                            Text = "The Charge at Feather River"
                        },
                        new
                        {
                            Id = 234,
                            IsCorrect = false,
                            QuestionId = 23,
                            Text = "Indiana Jones"
                        },
                        new
                        {
                            Id = 241,
                            IsCorrect = true,
                            QuestionId = 24,
                            Text = "Scimitar"
                        },
                        new
                        {
                            Id = 242,
                            IsCorrect = false,
                            QuestionId = 24,
                            Text = "Falchion"
                        },
                        new
                        {
                            Id = 243,
                            IsCorrect = false,
                            QuestionId = 24,
                            Text = "Ulfberht"
                        },
                        new
                        {
                            Id = 244,
                            IsCorrect = false,
                            QuestionId = 24,
                            Text = "Flamberge"
                        },
                        new
                        {
                            Id = 251,
                            IsCorrect = true,
                            QuestionId = 25,
                            Text = "Billy Loomis and Stu Macher"
                        },
                        new
                        {
                            Id = 252,
                            IsCorrect = false,
                            QuestionId = 25,
                            Text = "Dewey Riley"
                        },
                        new
                        {
                            Id = 253,
                            IsCorrect = false,
                            QuestionId = 25,
                            Text = "Sidney Prescott"
                        },
                        new
                        {
                            Id = 254,
                            IsCorrect = false,
                            QuestionId = 25,
                            Text = "Archie Prescott and Philip Marv"
                        },
                        new
                        {
                            Id = 261,
                            IsCorrect = true,
                            QuestionId = 26,
                            Text = "Daredevil"
                        },
                        new
                        {
                            Id = 262,
                            IsCorrect = false,
                            QuestionId = 26,
                            Text = "Thor"
                        },
                        new
                        {
                            Id = 263,
                            IsCorrect = false,
                            QuestionId = 26,
                            Text = "Wolverine"
                        },
                        new
                        {
                            Id = 264,
                            IsCorrect = false,
                            QuestionId = 26,
                            Text = "Hulk"
                        },
                        new
                        {
                            Id = 271,
                            IsCorrect = true,
                            QuestionId = 27,
                            Text = "United Kingdom"
                        },
                        new
                        {
                            Id = 272,
                            IsCorrect = false,
                            QuestionId = 27,
                            Text = "France"
                        },
                        new
                        {
                            Id = 273,
                            IsCorrect = false,
                            QuestionId = 27,
                            Text = "Italy"
                        },
                        new
                        {
                            Id = 274,
                            IsCorrect = false,
                            QuestionId = 27,
                            Text = "Germany"
                        },
                        new
                        {
                            Id = 281,
                            IsCorrect = true,
                            QuestionId = 28,
                            Text = "San Andreas"
                        },
                        new
                        {
                            Id = 282,
                            IsCorrect = false,
                            QuestionId = 28,
                            Text = "San Fierro"
                        },
                        new
                        {
                            Id = 283,
                            IsCorrect = false,
                            QuestionId = 28,
                            Text = "Las Venturas"
                        },
                        new
                        {
                            Id = 284,
                            IsCorrect = false,
                            QuestionId = 28,
                            Text = "Vice City"
                        },
                        new
                        {
                            Id = 291,
                            IsCorrect = true,
                            QuestionId = 29,
                            Text = "Wolowizard"
                        },
                        new
                        {
                            Id = 292,
                            IsCorrect = false,
                            QuestionId = 29,
                            Text = "Sheldor"
                        },
                        new
                        {
                            Id = 293,
                            IsCorrect = false,
                            QuestionId = 29,
                            Text = "Rajesh"
                        },
                        new
                        {
                            Id = 294,
                            IsCorrect = false,
                            QuestionId = 29,
                            Text = "Priya"
                        },
                        new
                        {
                            Id = 301,
                            IsCorrect = true,
                            QuestionId = 30,
                            Text = "Rebecca Sugar"
                        },
                        new
                        {
                            Id = 302,
                            IsCorrect = false,
                            QuestionId = 30,
                            Text = "Matt Burnett"
                        },
                        new
                        {
                            Id = 303,
                            IsCorrect = false,
                            QuestionId = 30,
                            Text = "Ian Jones Quartey"
                        },
                        new
                        {
                            Id = 304,
                            IsCorrect = false,
                            QuestionId = 30,
                            Text = "Ben Leven"
                        },
                        new
                        {
                            Id = 311,
                            IsCorrect = true,
                            QuestionId = 31,
                            Text = "Watch the Throne"
                        },
                        new
                        {
                            Id = 312,
                            IsCorrect = false,
                            QuestionId = 31,
                            Text = "Distant Relatives"
                        },
                        new
                        {
                            Id = 313,
                            IsCorrect = false,
                            QuestionId = 31,
                            Text = "What a Time to be Alive"
                        },
                        new
                        {
                            Id = 314,
                            IsCorrect = false,
                            QuestionId = 31,
                            Text = "Unfinished Business"
                        },
                        new
                        {
                            Id = 321,
                            IsCorrect = true,
                            QuestionId = 32,
                            Text = "Baffin Island"
                        },
                        new
                        {
                            Id = 322,
                            IsCorrect = false,
                            QuestionId = 32,
                            Text = "Prince Edward Island"
                        },
                        new
                        {
                            Id = 323,
                            IsCorrect = false,
                            QuestionId = 32,
                            Text = "Vancouver Island"
                        },
                        new
                        {
                            Id = 324,
                            IsCorrect = false,
                            QuestionId = 32,
                            Text = "Newfoundland"
                        },
                        new
                        {
                            Id = 331,
                            IsCorrect = true,
                            QuestionId = 33,
                            Text = "Kaunas"
                        },
                        new
                        {
                            Id = 332,
                            IsCorrect = false,
                            QuestionId = 33,
                            Text = "Panevėžys"
                        },
                        new
                        {
                            Id = 333,
                            IsCorrect = false,
                            QuestionId = 33,
                            Text = "Vilnius"
                        },
                        new
                        {
                            Id = 334,
                            IsCorrect = false,
                            QuestionId = 33,
                            Text = "Klaipėda"
                        },
                        new
                        {
                            Id = 341,
                            IsCorrect = true,
                            QuestionId = 34,
                            Text = "Aloysius O'Hare"
                        },
                        new
                        {
                            Id = 342,
                            IsCorrect = false,
                            QuestionId = 34,
                            Text = "Ted Wiggins"
                        },
                        new
                        {
                            Id = 343,
                            IsCorrect = false,
                            QuestionId = 34,
                            Text = "The Once-Ler"
                        },
                        new
                        {
                            Id = 344,
                            IsCorrect = false,
                            QuestionId = 34,
                            Text = "Grammy Norma"
                        },
                        new
                        {
                            Id = 351,
                            IsCorrect = true,
                            QuestionId = 35,
                            Text = "The Greasers"
                        },
                        new
                        {
                            Id = 352,
                            IsCorrect = false,
                            QuestionId = 35,
                            Text = "The Outsiders"
                        },
                        new
                        {
                            Id = 353,
                            IsCorrect = false,
                            QuestionId = 35,
                            Text = "The Mafia"
                        },
                        new
                        {
                            Id = 354,
                            IsCorrect = false,
                            QuestionId = 35,
                            Text = "The Socs"
                        },
                        new
                        {
                            Id = 361,
                            IsCorrect = true,
                            QuestionId = 36,
                            Text = "364"
                        },
                        new
                        {
                            Id = 362,
                            IsCorrect = false,
                            QuestionId = 36,
                            Text = "346"
                        },
                        new
                        {
                            Id = 363,
                            IsCorrect = false,
                            QuestionId = 36,
                            Text = "376"
                        },
                        new
                        {
                            Id = 364,
                            IsCorrect = false,
                            QuestionId = 36,
                            Text = "402"
                        },
                        new
                        {
                            Id = 371,
                            IsCorrect = true,
                            QuestionId = 37,
                            Text = "Once you have their money, you never give it back. "
                        },
                        new
                        {
                            Id = 372,
                            IsCorrect = false,
                            QuestionId = 37,
                            Text = "Never place friendship above profit"
                        },
                        new
                        {
                            Id = 373,
                            IsCorrect = false,
                            QuestionId = 37,
                            Text = "Greed is Eternal"
                        },
                        new
                        {
                            Id = 374,
                            IsCorrect = false,
                            QuestionId = 37,
                            Text = "Never allow family to stand in the way of opportunity"
                        },
                        new
                        {
                            Id = 381,
                            IsCorrect = true,
                            QuestionId = 38,
                            Text = "Germany"
                        },
                        new
                        {
                            Id = 382,
                            IsCorrect = false,
                            QuestionId = 38,
                            Text = "USA"
                        },
                        new
                        {
                            Id = 383,
                            IsCorrect = false,
                            QuestionId = 38,
                            Text = "Russia"
                        },
                        new
                        {
                            Id = 384,
                            IsCorrect = false,
                            QuestionId = 38,
                            Text = "China"
                        },
                        new
                        {
                            Id = 391,
                            IsCorrect = true,
                            QuestionId = 39,
                            Text = "169"
                        },
                        new
                        {
                            Id = 392,
                            IsCorrect = false,
                            QuestionId = 39,
                            Text = "100"
                        },
                        new
                        {
                            Id = 393,
                            IsCorrect = false,
                            QuestionId = 39,
                            Text = "132"
                        },
                        new
                        {
                            Id = 394,
                            IsCorrect = false,
                            QuestionId = 39,
                            Text = "245"
                        },
                        new
                        {
                            Id = 401,
                            IsCorrect = true,
                            QuestionId = 40,
                            Text = "1992"
                        },
                        new
                        {
                            Id = 402,
                            IsCorrect = false,
                            QuestionId = 40,
                            Text = "1989"
                        },
                        new
                        {
                            Id = 403,
                            IsCorrect = false,
                            QuestionId = 40,
                            Text = "1990"
                        },
                        new
                        {
                            Id = 404,
                            IsCorrect = false,
                            QuestionId = 40,
                            Text = "1994"
                        },
                        new
                        {
                            Id = 411,
                            IsCorrect = true,
                            QuestionId = 41,
                            Text = "Hewlett-Packard"
                        },
                        new
                        {
                            Id = 412,
                            IsCorrect = false,
                            QuestionId = 41,
                            Text = "Toshiba"
                        },
                        new
                        {
                            Id = 413,
                            IsCorrect = false,
                            QuestionId = 41,
                            Text = "Asus"
                        },
                        new
                        {
                            Id = 414,
                            IsCorrect = false,
                            QuestionId = 41,
                            Text = "Dell"
                        },
                        new
                        {
                            Id = 421,
                            IsCorrect = true,
                            QuestionId = 42,
                            Text = "Applejack"
                        },
                        new
                        {
                            Id = 422,
                            IsCorrect = false,
                            QuestionId = 42,
                            Text = "Twilight Sparkle"
                        },
                        new
                        {
                            Id = 423,
                            IsCorrect = false,
                            QuestionId = 42,
                            Text = "Pinkie Pie"
                        },
                        new
                        {
                            Id = 424,
                            IsCorrect = false,
                            QuestionId = 42,
                            Text = "Rarity"
                        },
                        new
                        {
                            Id = 431,
                            IsCorrect = true,
                            QuestionId = 43,
                            Text = "Showdown"
                        },
                        new
                        {
                            Id = 432,
                            IsCorrect = false,
                            QuestionId = 43,
                            Text = "Hadouken"
                        },
                        new
                        {
                            Id = 433,
                            IsCorrect = false,
                            QuestionId = 43,
                            Text = "Organ Grinder"
                        },
                        new
                        {
                            Id = 434,
                            IsCorrect = false,
                            QuestionId = 43,
                            Text = "Skewer"
                        },
                        new
                        {
                            Id = 441,
                            IsCorrect = true,
                            QuestionId = 44,
                            Text = "Christian Bale"
                        },
                        new
                        {
                            Id = 442,
                            IsCorrect = false,
                            QuestionId = 44,
                            Text = "Michael Caine"
                        },
                        new
                        {
                            Id = 443,
                            IsCorrect = false,
                            QuestionId = 44,
                            Text = "Ron Dean"
                        },
                        new
                        {
                            Id = 444,
                            IsCorrect = false,
                            QuestionId = 44,
                            Text = "Heath Ledger"
                        },
                        new
                        {
                            Id = 451,
                            IsCorrect = true,
                            QuestionId = 45,
                            Text = "April 29, 2008"
                        },
                        new
                        {
                            Id = 452,
                            IsCorrect = false,
                            QuestionId = 45,
                            Text = "May 21, 2009"
                        },
                        new
                        {
                            Id = 453,
                            IsCorrect = false,
                            QuestionId = 45,
                            Text = "June 22, 2010"
                        },
                        new
                        {
                            Id = 454,
                            IsCorrect = false,
                            QuestionId = 45,
                            Text = "July 28, 2008"
                        },
                        new
                        {
                            Id = 461,
                            IsCorrect = true,
                            QuestionId = 46,
                            Text = "Libra"
                        },
                        new
                        {
                            Id = 462,
                            IsCorrect = false,
                            QuestionId = 46,
                            Text = "Gemini"
                        },
                        new
                        {
                            Id = 463,
                            IsCorrect = false,
                            QuestionId = 46,
                            Text = "Taurus"
                        },
                        new
                        {
                            Id = 464,
                            IsCorrect = false,
                            QuestionId = 46,
                            Text = "Capricorn"
                        },
                        new
                        {
                            Id = 471,
                            IsCorrect = true,
                            QuestionId = 47,
                            Text = "Bones"
                        },
                        new
                        {
                            Id = 472,
                            IsCorrect = false,
                            QuestionId = 47,
                            Text = "Kyoto Animation"
                        },
                        new
                        {
                            Id = 473,
                            IsCorrect = false,
                            QuestionId = 47,
                            Text = "xebec"
                        },
                        new
                        {
                            Id = 474,
                            IsCorrect = false,
                            QuestionId = 47,
                            Text = "Production I.G"
                        },
                        new
                        {
                            Id = 481,
                            IsCorrect = true,
                            QuestionId = 48,
                            Text = "Titanic"
                        },
                        new
                        {
                            Id = 482,
                            IsCorrect = false,
                            QuestionId = 48,
                            Text = "Star Wars"
                        },
                        new
                        {
                            Id = 483,
                            IsCorrect = false,
                            QuestionId = 48,
                            Text = "Gone with the Wind"
                        },
                        new
                        {
                            Id = 484,
                            IsCorrect = false,
                            QuestionId = 48,
                            Text = "Jaws"
                        },
                        new
                        {
                            Id = 491,
                            IsCorrect = true,
                            QuestionId = 49,
                            Text = "North"
                        },
                        new
                        {
                            Id = 492,
                            IsCorrect = false,
                            QuestionId = 49,
                            Text = "3 Ninjas Kick Back"
                        },
                        new
                        {
                            Id = 493,
                            IsCorrect = false,
                            QuestionId = 49,
                            Text = "The Santa Clause"
                        },
                        new
                        {
                            Id = 494,
                            IsCorrect = false,
                            QuestionId = 49,
                            Text = "Richie Rich"
                        },
                        new
                        {
                            Id = 501,
                            IsCorrect = true,
                            QuestionId = 50,
                            Text = "Copper"
                        },
                        new
                        {
                            Id = 502,
                            IsCorrect = false,
                            QuestionId = 50,
                            Text = "Iron"
                        },
                        new
                        {
                            Id = 503,
                            IsCorrect = false,
                            QuestionId = 50,
                            Text = "Nickel"
                        },
                        new
                        {
                            Id = 504,
                            IsCorrect = false,
                            QuestionId = 50,
                            Text = "Silver"
                        });
                });

            modelBuilder.Entity("Quizzer.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Quizzer.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Text = "What breed of dog was Marley in the film \"Marley &amp; Me\" (2008)?"
                        },
                        new
                        {
                            Id = 2,
                            Text = "What is Scooby-Doo's real name?"
                        },
                        new
                        {
                            Id = 3,
                            Text = "In the Beatrix Potter books, what type of animal is Tommy Brock?"
                        },
                        new
                        {
                            Id = 4,
                            Text = "Which of the following created and directed the Katamari Damacy series?"
                        },
                        new
                        {
                            Id = 5,
                            Text = "What is the most common surname Wales?"
                        },
                        new
                        {
                            Id = 6,
                            Text = "Which internet company began life as an online bookstore called 'Cadabra'?"
                        },
                        new
                        {
                            Id = 7,
                            Text = "Which English football club has the nickname 'The Foxes'?"
                        },
                        new
                        {
                            Id = 8,
                            Text = "Which type of rock is created by intense heat AND pressure?"
                        },
                        new
                        {
                            Id = 9,
                            Text = "What does GHz stand for?"
                        },
                        new
                        {
                            Id = 10,
                            Text = "When was the programming language \"C#\" released?"
                        },
                        new
                        {
                            Id = 11,
                            Text = "On which continent is the country of Angola located?"
                        },
                        new
                        {
                            Id = 12,
                            Text = "Which of these artists do NOT originate from France?"
                        },
                        new
                        {
                            Id = 13,
                            Text = "Which of these is NOT a playable character in the 2016 video game Overwatch?"
                        },
                        new
                        {
                            Id = 14,
                            Text = "Which of the following films was Don Bluth both the writer, director, and producer for?"
                        },
                        new
                        {
                            Id = 15,
                            Text = "Which of the following Arab countries does NOT have a flag containing only Pan-Arab colours?"
                        },
                        new
                        {
                            Id = 16,
                            Text = "In most FPS video games such as Counter-Strike, shooting which part of the body does the highest damage?"
                        },
                        new
                        {
                            Id = 17,
                            Text = "What is the name of Broadway's first \"long-run\" musical?"
                        },
                        new
                        {
                            Id = 18,
                            Text = "If you play the Super Mario RPG and nap in a rented hotel room, you will wake up next to what familiar looking character?"
                        },
                        new
                        {
                            Id = 19,
                            Text = "Which movie of film director Stanley Kubrick is known to be an adaptation of a Stephen King novel?"
                        },
                        new
                        {
                            Id = 20,
                            Text = "Which band released songs suchs as \"Rio\", \"Girls on Film\", and \"The Reflex\"?"
                        },
                        new
                        {
                            Id = 21,
                            Text = "Dee from \"It's Always Sunny in Philadelphia\" has dated all of the following guys EXCEPT"
                        },
                        new
                        {
                            Id = 22,
                            Text = "In an orchestra, what is the lowest member of the brass family?"
                        },
                        new
                        {
                            Id = 23,
                            Text = "What was the first movie to ever use a Wilhelm Scream?"
                        },
                        new
                        {
                            Id = 24,
                            Text = "Which one of these is not a typical European sword design?"
                        },
                        new
                        {
                            Id = 25,
                            Text = "In the movie \"Scream\" who is Ghost Face?"
                        },
                        new
                        {
                            Id = 26,
                            Text = "This Marvel superhero is often called \"The man without fear\"."
                        },
                        new
                        {
                            Id = 27,
                            Text = "The 2002 film \"28 Days Later\" is mainly set in which European country?"
                        },
                        new
                        {
                            Id = 28,
                            Text = "Which of these is not the name of a city in the Grand Theft Auto series?"
                        },
                        new
                        {
                            Id = 29,
                            Text = "In \"The Big Bang Theory\", what is Howard Wolowitz's nickname in World of Warcraft?"
                        },
                        new
                        {
                            Id = 30,
                            Text = "Who designed the album cover for True Romance, an album by Estelle?"
                        },
                        new
                        {
                            Id = 31,
                            Text = "What collaborative album was released by Kanye West and Jay-Z in 2011?"
                        },
                        new
                        {
                            Id = 32,
                            Text = "What is Canada's largest island?"
                        },
                        new
                        {
                            Id = 33,
                            Text = "What is the second-largest city in Lithuania?"
                        },
                        new
                        {
                            Id = 34,
                            Text = "In the 2012 film, \"The Lorax\", who is the antagonist?"
                        },
                        new
                        {
                            Id = 35,
                            Text = "What is the name of the gang that Ponyboy is a part of in the book, The Outsiders?"
                        },
                        new
                        {
                            Id = 36,
                            Text = "The LS2 engine is how many cubic inches?"
                        },
                        new
                        {
                            Id = 37,
                            Text = "In \"Star Trek\", what is the Ferengi's First Rule of Acquisition?"
                        },
                        new
                        {
                            Id = 38,
                            Text = "Which of the following countries was the first to send an object into space?"
                        },
                        new
                        {
                            Id = 39,
                            Text = "How many aces can be shot down through the entirety of \"Ace Combat Zero: The Belkan War\"?"
                        },
                        new
                        {
                            Id = 40,
                            Text = "What year did \"Bishoujo Senshi Sailor Moon\" air in Japan?"
                        },
                        new
                        {
                            Id = 41,
                            Text = "Computer manufacturer Compaq was acquired for $25 billion dollars in 2002 by which company?"
                        },
                        new
                        {
                            Id = 42,
                            Text = "In \"My Little Pony: Friendship is Magic\", which of these ponies represents the quality of honesty?"
                        },
                        new
                        {
                            Id = 43,
                            Text = "In \"Team Fortress 2\", what is the fastest taunt kill that can be pulled off?"
                        },
                        new
                        {
                            Id = 44,
                            Text = "Who plays \"Bruce Wayne\" in the 2008 movie \"The Dark Knight\"?"
                        },
                        new
                        {
                            Id = 45,
                            Text = "What was the release date of \"Grand Theft Auto IV\"?"
                        },
                        new
                        {
                            Id = 46,
                            Text = "Which sign of the zodiac comes between Virgo and Scorpio?"
                        },
                        new
                        {
                            Id = 47,
                            Text = "Which studio animated Soul Eater?"
                        },
                        new
                        {
                            Id = 48,
                            Text = "What film did James Cameron's Avatar dethrone as the highest-grossing film ever?"
                        },
                        new
                        {
                            Id = 49,
                            Text = "Which 1994 film did Roger Ebert famously despise, saying \"I hated hated hated hated hated this movie\"."
                        },
                        new
                        {
                            Id = 50,
                            Text = "Located in Chile, El Teniente is the world's largest underground mine for what metal?"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Quizzer.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Quizzer.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Quizzer.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Quizzer.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Quizzer.Models.Answer", b =>
                {
                    b.HasOne("Quizzer.Models.Question", null)
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Quizzer.Models.ApplicationUser", b =>
                {
                    b.OwnsMany("Quizzer.Models.ScoreEntry", "ScoreEntries", b1 =>
                        {
                            b1.Property<string>("ApplicationUserId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("QuizPlayerId")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("Score")
                                .HasColumnType("int");

                            b1.HasKey("ApplicationUserId", "Id");

                            b1.ToTable("ScoreEntries");

                            b1.WithOwner()
                                .HasForeignKey("ApplicationUserId");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
