// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Quizzer.Data;

namespace Quizzer.Data.Migrations
{
    [DbContext(typeof(QuizDbContext))]
    [Migration("20200609193109_IntitialCreate")]
    partial class IntitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("IdentityServer4.EntityFramework.Entities.DeviceFlowCodes", b =>
                {
                    b.Property<string>("UserCode")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasMaxLength(50000);

                    b.Property<string>("DeviceCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<DateTime?>("Expiration")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("SubjectId")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.HasKey("UserCode");

                    b.HasIndex("DeviceCode")
                        .IsUnique();

                    b.HasIndex("Expiration");

                    b.ToTable("DeviceCodes");
                });

            modelBuilder.Entity("IdentityServer4.EntityFramework.Entities.PersistedGrant", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasMaxLength(50000);

                    b.Property<DateTime?>("Expiration")
                        .HasColumnType("datetime2");

                    b.Property<string>("SubjectId")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Key");

                    b.HasIndex("Expiration");

                    b.HasIndex("SubjectId", "ClientId", "Type");

                    b.ToTable("PersistedGrants");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Quizzer.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Quizzer.Models.Option", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("Options");

                    b.HasData(
                        new
                        {
                            Id = 11,
                            IsCorrect = true,
                            QuestionId = 1,
                            Text = "Viola"
                        },
                        new
                        {
                            Id = 12,
                            IsCorrect = false,
                            QuestionId = 1,
                            Text = "Oboe"
                        },
                        new
                        {
                            Id = 13,
                            IsCorrect = false,
                            QuestionId = 1,
                            Text = "Trombone"
                        },
                        new
                        {
                            Id = 14,
                            IsCorrect = false,
                            QuestionId = 1,
                            Text = "Duduk"
                        },
                        new
                        {
                            Id = 21,
                            IsCorrect = true,
                            QuestionId = 2,
                            Text = "Springfield, Oregon"
                        },
                        new
                        {
                            Id = 22,
                            IsCorrect = false,
                            QuestionId = 2,
                            Text = "Springfield, Missouri"
                        },
                        new
                        {
                            Id = 23,
                            IsCorrect = false,
                            QuestionId = 2,
                            Text = "Springfield, Illinois"
                        },
                        new
                        {
                            Id = 24,
                            IsCorrect = false,
                            QuestionId = 2,
                            Text = "Springfield, Massachusetts"
                        },
                        new
                        {
                            Id = 31,
                            IsCorrect = true,
                            QuestionId = 3,
                            Text = "Active Directory"
                        },
                        new
                        {
                            Id = 32,
                            IsCorrect = false,
                            QuestionId = 3,
                            Text = "Alternative Drive"
                        },
                        new
                        {
                            Id = 33,
                            IsCorrect = false,
                            QuestionId = 3,
                            Text = "Automated Database"
                        },
                        new
                        {
                            Id = 34,
                            IsCorrect = false,
                            QuestionId = 3,
                            Text = "Active Department"
                        },
                        new
                        {
                            Id = 41,
                            IsCorrect = true,
                            QuestionId = 4,
                            Text = "3.14159"
                        },
                        new
                        {
                            Id = 42,
                            IsCorrect = false,
                            QuestionId = 4,
                            Text = "3.14169"
                        },
                        new
                        {
                            Id = 43,
                            IsCorrect = false,
                            QuestionId = 4,
                            Text = "3.12423"
                        },
                        new
                        {
                            Id = 44,
                            IsCorrect = false,
                            QuestionId = 4,
                            Text = "3.25812"
                        },
                        new
                        {
                            Id = 51,
                            IsCorrect = true,
                            QuestionId = 5,
                            Text = "Jean"
                        },
                        new
                        {
                            Id = 52,
                            IsCorrect = false,
                            QuestionId = 5,
                            Text = "Jane"
                        },
                        new
                        {
                            Id = 53,
                            IsCorrect = false,
                            QuestionId = 5,
                            Text = "Emma"
                        },
                        new
                        {
                            Id = 54,
                            IsCorrect = false,
                            QuestionId = 5,
                            Text = "Jo"
                        },
                        new
                        {
                            Id = 61,
                            IsCorrect = true,
                            QuestionId = 6,
                            Text = "September 1, 1939"
                        },
                        new
                        {
                            Id = 62,
                            IsCorrect = false,
                            QuestionId = 6,
                            Text = "December 7, 1941"
                        },
                        new
                        {
                            Id = 63,
                            IsCorrect = false,
                            QuestionId = 6,
                            Text = "June 22, 1941"
                        },
                        new
                        {
                            Id = 64,
                            IsCorrect = false,
                            QuestionId = 6,
                            Text = "July 7, 1937"
                        },
                        new
                        {
                            Id = 71,
                            IsCorrect = true,
                            QuestionId = 7,
                            Text = "A GDC Document"
                        },
                        new
                        {
                            Id = 72,
                            IsCorrect = false,
                            QuestionId = 7,
                            Text = "Text Document on Herbs"
                        },
                        new
                        {
                            Id = 73,
                            IsCorrect = false,
                            QuestionId = 7,
                            Text = "Nothing"
                        },
                        new
                        {
                            Id = 74,
                            IsCorrect = false,
                            QuestionId = 7,
                            Text = "Document on B.O.Ws"
                        },
                        new
                        {
                            Id = 81,
                            IsCorrect = true,
                            QuestionId = 8,
                            Text = "Baauer"
                        },
                        new
                        {
                            Id = 82,
                            IsCorrect = false,
                            QuestionId = 8,
                            Text = "RL Grime"
                        },
                        new
                        {
                            Id = 83,
                            IsCorrect = false,
                            QuestionId = 8,
                            Text = "NGHTMRE"
                        },
                        new
                        {
                            Id = 84,
                            IsCorrect = false,
                            QuestionId = 8,
                            Text = "Flosstradamus"
                        },
                        new
                        {
                            Id = 91,
                            IsCorrect = true,
                            QuestionId = 9,
                            Text = "Post cards"
                        },
                        new
                        {
                            Id = 92,
                            IsCorrect = false,
                            QuestionId = 9,
                            Text = "Alcohol"
                        },
                        new
                        {
                            Id = 93,
                            IsCorrect = false,
                            QuestionId = 9,
                            Text = "Cigarettes"
                        },
                        new
                        {
                            Id = 94,
                            IsCorrect = false,
                            QuestionId = 9,
                            Text = "Sodas "
                        },
                        new
                        {
                            Id = 101,
                            IsCorrect = true,
                            QuestionId = 10,
                            Text = "Vulpes Vulpes"
                        },
                        new
                        {
                            Id = 102,
                            IsCorrect = false,
                            QuestionId = 10,
                            Text = "Vulpes Redus"
                        },
                        new
                        {
                            Id = 103,
                            IsCorrect = false,
                            QuestionId = 10,
                            Text = "Red Fox"
                        },
                        new
                        {
                            Id = 104,
                            IsCorrect = false,
                            QuestionId = 10,
                            Text = "Vulpes Vulpie"
                        },
                        new
                        {
                            Id = 111,
                            IsCorrect = true,
                            QuestionId = 11,
                            Text = "Mario Party 4"
                        },
                        new
                        {
                            Id = 112,
                            IsCorrect = false,
                            QuestionId = 11,
                            Text = "New Super Mario Bros."
                        },
                        new
                        {
                            Id = 113,
                            IsCorrect = false,
                            QuestionId = 11,
                            Text = "Mario Kart Wii"
                        },
                        new
                        {
                            Id = 114,
                            IsCorrect = false,
                            QuestionId = 11,
                            Text = "Super Mario 3D World"
                        },
                        new
                        {
                            Id = 121,
                            IsCorrect = true,
                            QuestionId = 12,
                            Text = "Sony"
                        },
                        new
                        {
                            Id = 122,
                            IsCorrect = false,
                            QuestionId = 12,
                            Text = "Panasonic"
                        },
                        new
                        {
                            Id = 123,
                            IsCorrect = false,
                            QuestionId = 12,
                            Text = "LG"
                        },
                        new
                        {
                            Id = 124,
                            IsCorrect = false,
                            QuestionId = 12,
                            Text = "Fujitsu"
                        },
                        new
                        {
                            Id = 131,
                            IsCorrect = true,
                            QuestionId = 13,
                            Text = "Koenigsegg"
                        },
                        new
                        {
                            Id = 132,
                            IsCorrect = false,
                            QuestionId = 13,
                            Text = "Bugatti"
                        },
                        new
                        {
                            Id = 133,
                            IsCorrect = false,
                            QuestionId = 13,
                            Text = "Lamborghini"
                        },
                        new
                        {
                            Id = 134,
                            IsCorrect = false,
                            QuestionId = 13,
                            Text = "McLaren"
                        },
                        new
                        {
                            Id = 141,
                            IsCorrect = true,
                            QuestionId = 14,
                            Text = "Kazakhstan"
                        },
                        new
                        {
                            Id = 142,
                            IsCorrect = false,
                            QuestionId = 14,
                            Text = "Russia"
                        },
                        new
                        {
                            Id = 143,
                            IsCorrect = false,
                            QuestionId = 14,
                            Text = "Iran"
                        },
                        new
                        {
                            Id = 144,
                            IsCorrect = false,
                            QuestionId = 14,
                            Text = "United States"
                        },
                        new
                        {
                            Id = 151,
                            IsCorrect = true,
                            QuestionId = 15,
                            Text = "Delaware"
                        },
                        new
                        {
                            Id = 152,
                            IsCorrect = false,
                            QuestionId = 15,
                            Text = "Rhode Island"
                        },
                        new
                        {
                            Id = 153,
                            IsCorrect = false,
                            QuestionId = 15,
                            Text = "Maine"
                        },
                        new
                        {
                            Id = 154,
                            IsCorrect = false,
                            QuestionId = 15,
                            Text = "Virginia"
                        },
                        new
                        {
                            Id = 161,
                            IsCorrect = true,
                            QuestionId = 16,
                            Text = "Carbon"
                        },
                        new
                        {
                            Id = 162,
                            IsCorrect = false,
                            QuestionId = 16,
                            Text = "Tungsten"
                        },
                        new
                        {
                            Id = 163,
                            IsCorrect = false,
                            QuestionId = 16,
                            Text = "Platinum"
                        },
                        new
                        {
                            Id = 164,
                            IsCorrect = false,
                            QuestionId = 16,
                            Text = "Osmium"
                        },
                        new
                        {
                            Id = 171,
                            IsCorrect = true,
                            QuestionId = 17,
                            Text = "Dr.Dre"
                        },
                        new
                        {
                            Id = 172,
                            IsCorrect = false,
                            QuestionId = 17,
                            Text = "Ol' Dirty Bastard"
                        },
                        new
                        {
                            Id = 173,
                            IsCorrect = false,
                            QuestionId = 17,
                            Text = "GZA"
                        },
                        new
                        {
                            Id = 174,
                            IsCorrect = false,
                            QuestionId = 17,
                            Text = "Method Man"
                        },
                        new
                        {
                            Id = 181,
                            IsCorrect = true,
                            QuestionId = 18,
                            Text = "Blue Sky"
                        },
                        new
                        {
                            Id = 182,
                            IsCorrect = false,
                            QuestionId = 18,
                            Text = "Baby Blue"
                        },
                        new
                        {
                            Id = 183,
                            IsCorrect = false,
                            QuestionId = 18,
                            Text = "Rock Candy"
                        },
                        new
                        {
                            Id = 184,
                            IsCorrect = false,
                            QuestionId = 18,
                            Text = "Pure Glass"
                        },
                        new
                        {
                            Id = 191,
                            IsCorrect = true,
                            QuestionId = 19,
                            Text = "Red Special"
                        },
                        new
                        {
                            Id = 192,
                            IsCorrect = false,
                            QuestionId = 19,
                            Text = "Blue Special"
                        },
                        new
                        {
                            Id = 193,
                            IsCorrect = false,
                            QuestionId = 19,
                            Text = "Green Special"
                        },
                        new
                        {
                            Id = 194,
                            IsCorrect = false,
                            QuestionId = 19,
                            Text = "Yellow Special"
                        },
                        new
                        {
                            Id = 201,
                            IsCorrect = true,
                            QuestionId = 20,
                            Text = "Min"
                        },
                        new
                        {
                            Id = 202,
                            IsCorrect = false,
                            QuestionId = 20,
                            Text = "Menu"
                        },
                        new
                        {
                            Id = 203,
                            IsCorrect = false,
                            QuestionId = 20,
                            Text = "Mut"
                        },
                        new
                        {
                            Id = 204,
                            IsCorrect = false,
                            QuestionId = 20,
                            Text = "Meret"
                        },
                        new
                        {
                            Id = 211,
                            IsCorrect = true,
                            QuestionId = 21,
                            Text = "9"
                        },
                        new
                        {
                            Id = 212,
                            IsCorrect = false,
                            QuestionId = 21,
                            Text = "4"
                        },
                        new
                        {
                            Id = 213,
                            IsCorrect = false,
                            QuestionId = 21,
                            Text = "7"
                        },
                        new
                        {
                            Id = 214,
                            IsCorrect = false,
                            QuestionId = 21,
                            Text = "2"
                        },
                        new
                        {
                            Id = 221,
                            IsCorrect = true,
                            QuestionId = 22,
                            Text = "Maori"
                        },
                        new
                        {
                            Id = 222,
                            IsCorrect = false,
                            QuestionId = 22,
                            Text = "Vikings"
                        },
                        new
                        {
                            Id = 223,
                            IsCorrect = false,
                            QuestionId = 22,
                            Text = "Polynesians"
                        },
                        new
                        {
                            Id = 224,
                            IsCorrect = false,
                            QuestionId = 22,
                            Text = "Samoans"
                        },
                        new
                        {
                            Id = 231,
                            IsCorrect = true,
                            QuestionId = 23,
                            Text = "LazyTown"
                        },
                        new
                        {
                            Id = 232,
                            IsCorrect = false,
                            QuestionId = 23,
                            Text = "Sofia the First"
                        },
                        new
                        {
                            Id = 233,
                            IsCorrect = false,
                            QuestionId = 23,
                            Text = "DuckTales"
                        },
                        new
                        {
                            Id = 234,
                            IsCorrect = false,
                            QuestionId = 23,
                            Text = "Tom and Jerry"
                        },
                        new
                        {
                            Id = 241,
                            IsCorrect = true,
                            QuestionId = 24,
                            Text = "AlunaGeorge"
                        },
                        new
                        {
                            Id = 242,
                            IsCorrect = false,
                            QuestionId = 24,
                            Text = "DJ Snake"
                        },
                        new
                        {
                            Id = 243,
                            IsCorrect = false,
                            QuestionId = 24,
                            Text = "Steve Aoki"
                        },
                        new
                        {
                            Id = 244,
                            IsCorrect = false,
                            QuestionId = 24,
                            Text = "Major Lazer"
                        },
                        new
                        {
                            Id = 251,
                            IsCorrect = true,
                            QuestionId = 25,
                            Text = "John O'Groats"
                        },
                        new
                        {
                            Id = 252,
                            IsCorrect = false,
                            QuestionId = 25,
                            Text = "Brawl"
                        },
                        new
                        {
                            Id = 253,
                            IsCorrect = false,
                            QuestionId = 25,
                            Text = "Kearvaig"
                        },
                        new
                        {
                            Id = 254,
                            IsCorrect = false,
                            QuestionId = 25,
                            Text = "Talmine"
                        },
                        new
                        {
                            Id = 261,
                            IsCorrect = true,
                            QuestionId = 26,
                            Text = "Blank"
                        },
                        new
                        {
                            Id = 262,
                            IsCorrect = false,
                            QuestionId = 26,
                            Text = "Immanity"
                        },
                        new
                        {
                            Id = 263,
                            IsCorrect = false,
                            QuestionId = 26,
                            Text = "Disboard"
                        },
                        new
                        {
                            Id = 264,
                            IsCorrect = false,
                            QuestionId = 26,
                            Text = "Warbeasts"
                        },
                        new
                        {
                            Id = 271,
                            IsCorrect = true,
                            QuestionId = 27,
                            Text = "Rank 1 Legend"
                        },
                        new
                        {
                            Id = 272,
                            IsCorrect = false,
                            QuestionId = 27,
                            Text = "Rank 1 Elite"
                        },
                        new
                        {
                            Id = 273,
                            IsCorrect = false,
                            QuestionId = 27,
                            Text = "Rank 1 Master"
                        },
                        new
                        {
                            Id = 274,
                            IsCorrect = false,
                            QuestionId = 27,
                            Text = "Rank 1 Supreme"
                        },
                        new
                        {
                            Id = 281,
                            IsCorrect = true,
                            QuestionId = 28,
                            Text = "Radiation's Earthbound Halloween Hack"
                        },
                        new
                        {
                            Id = 282,
                            IsCorrect = false,
                            QuestionId = 28,
                            Text = "Homestuck: [S] Wake"
                        },
                        new
                        {
                            Id = 283,
                            IsCorrect = false,
                            QuestionId = 28,
                            Text = "Undertale"
                        },
                        new
                        {
                            Id = 284,
                            IsCorrect = false,
                            QuestionId = 28,
                            Text = "Mother: Cognitive Dissonance"
                        },
                        new
                        {
                            Id = 291,
                            IsCorrect = true,
                            QuestionId = 29,
                            Text = "Non-impact printer"
                        },
                        new
                        {
                            Id = 292,
                            IsCorrect = false,
                            QuestionId = 29,
                            Text = "Impact printer"
                        },
                        new
                        {
                            Id = 293,
                            IsCorrect = false,
                            QuestionId = 29,
                            Text = "Daisywheel printer"
                        },
                        new
                        {
                            Id = 294,
                            IsCorrect = false,
                            QuestionId = 29,
                            Text = "Dot matrix printer"
                        },
                        new
                        {
                            Id = 301,
                            IsCorrect = true,
                            QuestionId = 30,
                            Text = "1971"
                        },
                        new
                        {
                            Id = 302,
                            IsCorrect = false,
                            QuestionId = 30,
                            Text = "1975"
                        },
                        new
                        {
                            Id = 303,
                            IsCorrect = false,
                            QuestionId = 30,
                            Text = "1983"
                        },
                        new
                        {
                            Id = 304,
                            IsCorrect = false,
                            QuestionId = 30,
                            Text = "1969"
                        },
                        new
                        {
                            Id = 311,
                            IsCorrect = true,
                            QuestionId = 31,
                            Text = "Game Maker"
                        },
                        new
                        {
                            Id = 312,
                            IsCorrect = false,
                            QuestionId = 31,
                            Text = "Stencyl"
                        },
                        new
                        {
                            Id = 313,
                            IsCorrect = false,
                            QuestionId = 31,
                            Text = "Construct"
                        },
                        new
                        {
                            Id = 314,
                            IsCorrect = false,
                            QuestionId = 31,
                            Text = "Torque 2D"
                        },
                        new
                        {
                            Id = 321,
                            IsCorrect = true,
                            QuestionId = 32,
                            Text = "Shi No Numa"
                        },
                        new
                        {
                            Id = 322,
                            IsCorrect = false,
                            QuestionId = 32,
                            Text = "Tranzit"
                        },
                        new
                        {
                            Id = 323,
                            IsCorrect = false,
                            QuestionId = 32,
                            Text = "Kino Der Toten"
                        },
                        new
                        {
                            Id = 324,
                            IsCorrect = false,
                            QuestionId = 32,
                            Text = "Der Riese"
                        },
                        new
                        {
                            Id = 331,
                            IsCorrect = true,
                            QuestionId = 33,
                            Text = "15 pounds"
                        },
                        new
                        {
                            Id = 332,
                            IsCorrect = false,
                            QuestionId = 33,
                            Text = "20 pounds"
                        },
                        new
                        {
                            Id = 333,
                            IsCorrect = false,
                            QuestionId = 33,
                            Text = "10 pounds"
                        },
                        new
                        {
                            Id = 334,
                            IsCorrect = false,
                            QuestionId = 33,
                            Text = "30 pounds"
                        },
                        new
                        {
                            Id = 341,
                            IsCorrect = true,
                            QuestionId = 34,
                            Text = "Candles in the Wind"
                        },
                        new
                        {
                            Id = 342,
                            IsCorrect = false,
                            QuestionId = 34,
                            Text = "I Guess That's Why They Call It The Blues"
                        },
                        new
                        {
                            Id = 343,
                            IsCorrect = false,
                            QuestionId = 34,
                            Text = "Your Song"
                        },
                        new
                        {
                            Id = 344,
                            IsCorrect = false,
                            QuestionId = 34,
                            Text = "Island Girl"
                        },
                        new
                        {
                            Id = 351,
                            IsCorrect = true,
                            QuestionId = 35,
                            Text = "4"
                        },
                        new
                        {
                            Id = 352,
                            IsCorrect = false,
                            QuestionId = 35,
                            Text = "8"
                        },
                        new
                        {
                            Id = 353,
                            IsCorrect = false,
                            QuestionId = 35,
                            Text = "6"
                        },
                        new
                        {
                            Id = 354,
                            IsCorrect = false,
                            QuestionId = 35,
                            Text = "2"
                        },
                        new
                        {
                            Id = 361,
                            IsCorrect = true,
                            QuestionId = 36,
                            Text = "Californian"
                        },
                        new
                        {
                            Id = 362,
                            IsCorrect = false,
                            QuestionId = 36,
                            Text = "Carpathia"
                        },
                        new
                        {
                            Id = 363,
                            IsCorrect = false,
                            QuestionId = 36,
                            Text = "Cristol"
                        },
                        new
                        {
                            Id = 364,
                            IsCorrect = false,
                            QuestionId = 36,
                            Text = "Commerce"
                        },
                        new
                        {
                            Id = 371,
                            IsCorrect = true,
                            QuestionId = 37,
                            Text = "Blinkmoth Infusion"
                        },
                        new
                        {
                            Id = 372,
                            IsCorrect = false,
                            QuestionId = 37,
                            Text = "Vitalizing Wind"
                        },
                        new
                        {
                            Id = 373,
                            IsCorrect = false,
                            QuestionId = 37,
                            Text = " Chant of Vitu-Ghazi"
                        },
                        new
                        {
                            Id = 374,
                            IsCorrect = false,
                            QuestionId = 37,
                            Text = "Assert Authority"
                        },
                        new
                        {
                            Id = 381,
                            IsCorrect = true,
                            QuestionId = 38,
                            Text = "Kelly Clarkson"
                        },
                        new
                        {
                            Id = 382,
                            IsCorrect = false,
                            QuestionId = 38,
                            Text = "Justin Guarini"
                        },
                        new
                        {
                            Id = 383,
                            IsCorrect = false,
                            QuestionId = 38,
                            Text = "Ruben Studdard"
                        },
                        new
                        {
                            Id = 384,
                            IsCorrect = false,
                            QuestionId = 38,
                            Text = "Chris Daughtry"
                        },
                        new
                        {
                            Id = 391,
                            IsCorrect = true,
                            QuestionId = 39,
                            Text = "Pelekai"
                        },
                        new
                        {
                            Id = 392,
                            IsCorrect = false,
                            QuestionId = 39,
                            Text = "Anoaʻi"
                        },
                        new
                        {
                            Id = 393,
                            IsCorrect = false,
                            QuestionId = 39,
                            Text = "Kealoha"
                        },
                        new
                        {
                            Id = 394,
                            IsCorrect = false,
                            QuestionId = 39,
                            Text = "Kuʻulei"
                        },
                        new
                        {
                            Id = 401,
                            IsCorrect = true,
                            QuestionId = 40,
                            Text = "84 Earth years"
                        },
                        new
                        {
                            Id = 402,
                            IsCorrect = false,
                            QuestionId = 40,
                            Text = "47 Earth years"
                        },
                        new
                        {
                            Id = 403,
                            IsCorrect = false,
                            QuestionId = 40,
                            Text = "62 Earth years"
                        },
                        new
                        {
                            Id = 404,
                            IsCorrect = false,
                            QuestionId = 40,
                            Text = "109 Earth years"
                        },
                        new
                        {
                            Id = 411,
                            IsCorrect = true,
                            QuestionId = 41,
                            Text = "Shaquille O'Neal"
                        },
                        new
                        {
                            Id = 412,
                            IsCorrect = false,
                            QuestionId = 41,
                            Text = "Allen Iverson"
                        },
                        new
                        {
                            Id = 413,
                            IsCorrect = false,
                            QuestionId = 41,
                            Text = "Kobe Bryant"
                        },
                        new
                        {
                            Id = 414,
                            IsCorrect = false,
                            QuestionId = 41,
                            Text = "Paul Pierce"
                        },
                        new
                        {
                            Id = 421,
                            IsCorrect = true,
                            QuestionId = 42,
                            Text = "Hampshire"
                        },
                        new
                        {
                            Id = 422,
                            IsCorrect = false,
                            QuestionId = 42,
                            Text = "Oxfordshire"
                        },
                        new
                        {
                            Id = 423,
                            IsCorrect = false,
                            QuestionId = 42,
                            Text = "Buckinghamshire"
                        },
                        new
                        {
                            Id = 424,
                            IsCorrect = false,
                            QuestionId = 42,
                            Text = "Surrey"
                        },
                        new
                        {
                            Id = 431,
                            IsCorrect = true,
                            QuestionId = 43,
                            Text = "Camino Island"
                        },
                        new
                        {
                            Id = 432,
                            IsCorrect = false,
                            QuestionId = 43,
                            Text = "Rogue Lawyer"
                        },
                        new
                        {
                            Id = 433,
                            IsCorrect = false,
                            QuestionId = 43,
                            Text = "Gray Mountain"
                        },
                        new
                        {
                            Id = 434,
                            IsCorrect = false,
                            QuestionId = 43,
                            Text = "The Litigators"
                        },
                        new
                        {
                            Id = 441,
                            IsCorrect = true,
                            QuestionId = 44,
                            Text = "Ronald Reagan"
                        },
                        new
                        {
                            Id = 442,
                            IsCorrect = false,
                            QuestionId = 44,
                            Text = "Jimmy Carter"
                        },
                        new
                        {
                            Id = 443,
                            IsCorrect = false,
                            QuestionId = 44,
                            Text = "Gerald Ford"
                        },
                        new
                        {
                            Id = 444,
                            IsCorrect = false,
                            QuestionId = 44,
                            Text = "Richard Nixon"
                        },
                        new
                        {
                            Id = 451,
                            IsCorrect = true,
                            QuestionId = 45,
                            Text = "Longclaw"
                        },
                        new
                        {
                            Id = 452,
                            IsCorrect = false,
                            QuestionId = 45,
                            Text = "Oathkeeper"
                        },
                        new
                        {
                            Id = 453,
                            IsCorrect = false,
                            QuestionId = 45,
                            Text = "Widow's Wail"
                        },
                        new
                        {
                            Id = 454,
                            IsCorrect = false,
                            QuestionId = 45,
                            Text = "Needle"
                        },
                        new
                        {
                            Id = 461,
                            IsCorrect = true,
                            QuestionId = 46,
                            Text = "6"
                        },
                        new
                        {
                            Id = 462,
                            IsCorrect = false,
                            QuestionId = 46,
                            Text = "7"
                        },
                        new
                        {
                            Id = 463,
                            IsCorrect = false,
                            QuestionId = 46,
                            Text = "8"
                        },
                        new
                        {
                            Id = 464,
                            IsCorrect = false,
                            QuestionId = 46,
                            Text = "5"
                        },
                        new
                        {
                            Id = 471,
                            IsCorrect = true,
                            QuestionId = 47,
                            Text = "Mermaid Transformation"
                        },
                        new
                        {
                            Id = 472,
                            IsCorrect = false,
                            QuestionId = 47,
                            Text = "Artificial Gills"
                        },
                        new
                        {
                            Id = 473,
                            IsCorrect = false,
                            QuestionId = 47,
                            Text = "Bubble Head"
                        },
                        new
                        {
                            Id = 474,
                            IsCorrect = false,
                            QuestionId = 47,
                            Text = "Bubble Shield"
                        },
                        new
                        {
                            Id = 481,
                            IsCorrect = true,
                            QuestionId = 48,
                            Text = "Atlantic Plate"
                        },
                        new
                        {
                            Id = 482,
                            IsCorrect = false,
                            QuestionId = 48,
                            Text = "North American Plate"
                        },
                        new
                        {
                            Id = 483,
                            IsCorrect = false,
                            QuestionId = 48,
                            Text = "Eurasian Plate"
                        },
                        new
                        {
                            Id = 484,
                            IsCorrect = false,
                            QuestionId = 48,
                            Text = "Nazca Plate"
                        },
                        new
                        {
                            Id = 491,
                            IsCorrect = true,
                            QuestionId = 49,
                            Text = "Bobby Shmurda"
                        },
                        new
                        {
                            Id = 492,
                            IsCorrect = false,
                            QuestionId = 49,
                            Text = "DJ Snake"
                        },
                        new
                        {
                            Id = 493,
                            IsCorrect = false,
                            QuestionId = 49,
                            Text = "Swae Lee"
                        },
                        new
                        {
                            Id = 494,
                            IsCorrect = false,
                            QuestionId = 49,
                            Text = "Young Thug"
                        },
                        new
                        {
                            Id = 501,
                            IsCorrect = true,
                            QuestionId = 50,
                            Text = "Java Virtual Machine"
                        },
                        new
                        {
                            Id = 502,
                            IsCorrect = false,
                            QuestionId = 50,
                            Text = "Java Vendor Machine"
                        },
                        new
                        {
                            Id = 503,
                            IsCorrect = false,
                            QuestionId = 50,
                            Text = "Java Visual Machine"
                        },
                        new
                        {
                            Id = 504,
                            IsCorrect = false,
                            QuestionId = 50,
                            Text = "Just Virtual Machine"
                        });
                });

            modelBuilder.Entity("Quizzer.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Text = "What is not a wind instrument?"
                        },
                        new
                        {
                            Id = 2,
                            Text = "What town was \"Springfield\" from \"The Simpsons\" originally named after?"
                        },
                        new
                        {
                            Id = 3,
                            Text = "What does AD stand for in relation to Windows Operating Systems? "
                        },
                        new
                        {
                            Id = 4,
                            Text = "What are the first 6 digits of the number \"Pi\"?"
                        },
                        new
                        {
                            Id = 5,
                            Text = "What is Hermione Granger's middle name?"
                        },
                        new
                        {
                            Id = 6,
                            Text = "On what day did Germany invade Poland?"
                        },
                        new
                        {
                            Id = 7,
                            Text = "In the Gamecube Version of \"Resident Evil\" what text document is open on the monitor of the computer in the Visual Data Room?"
                        },
                        new
                        {
                            Id = 8,
                            Text = "Which artist released the 2012 single \"Harlem Shake\", which was used in numerous YouTube videos in 2013?"
                        },
                        new
                        {
                            Id = 9,
                            Text = "What did the first vending machines in the early 1880's dispense?"
                        },
                        new
                        {
                            Id = 10,
                            Text = "What is the scientific name of the red fox?"
                        },
                        new
                        {
                            Id = 11,
                            Text = "In which Mario game did the Mega Mushroom make its debut?"
                        },
                        new
                        {
                            Id = 12,
                            Text = "Which company designed the \"Betamax\" video cassette format?"
                        },
                        new
                        {
                            Id = 13,
                            Text = "Which supercar company is from Sweden?"
                        },
                        new
                        {
                            Id = 14,
                            Text = "Where is the world's oldest still operational space launch facility located?"
                        },
                        new
                        {
                            Id = 15,
                            Text = "What is the oldest US state?"
                        },
                        new
                        {
                            Id = 16,
                            Text = "Which element has the highest melting point?"
                        },
                        new
                        {
                            Id = 17,
                            Text = "Which one of these rappers is NOT a member of the rap group Wu-Tang Clan?"
                        },
                        new
                        {
                            Id = 18,
                            Text = "In the television show Breaking Bad, what is the street name of Walter and Jesse's notorious product?"
                        },
                        new
                        {
                            Id = 19,
                            Text = "What is Brian May's guitar called?"
                        },
                        new
                        {
                            Id = 20,
                            Text = "Who is the Egyptian god of reproduction and lettuce?"
                        },
                        new
                        {
                            Id = 21,
                            Text = "What is the 100th digit of Pi?"
                        },
                        new
                        {
                            Id = 22,
                            Text = "What is the name of New Zealand's indigenous people?"
                        },
                        new
                        {
                            Id = 23,
                            Text = "Which show is known for the songs \"You are a Pirate\", \"Cooking by the Book\" and \"We Are Number One\"?"
                        },
                        new
                        {
                            Id = 24,
                            Text = "Who wrote the song \"You Know You Like It\"?"
                        },
                        new
                        {
                            Id = 25,
                            Text = "Which town was Seamus \"Sledge\" Cowden from \"Tom Clancy's Rainbow Six Siege\" born in?"
                        },
                        new
                        {
                            Id = 26,
                            Text = "The two main characters of \"No Game No Life\", Sora and Shiro, together go by what name?"
                        },
                        new
                        {
                            Id = 27,
                            Text = "In the game \"Hearthstone\", what is the best rank possible?"
                        },
                        new
                        {
                            Id = 28,
                            Text = "Toby Fox's \"Megalovania\" was first used where?"
                        },
                        new
                        {
                            Id = 29,
                            Text = "Laserjet and inkjet printers are both examples of what type of printer?"
                        },
                        new
                        {
                            Id = 30,
                            Text = "In what year did Clint Eastwood star as Inspector Harry Callahan in the film \"Dirty Harry\"?"
                        },
                        new
                        {
                            Id = 31,
                            Text = "Dutch computer scientist Mark Overmars is known for creating which game development engine?"
                        },
                        new
                        {
                            Id = 32,
                            Text = "Which was the first \"Call Of Duty: Zombies\" map to introduce the \"Wunderwaffe DG-2\"?"
                        },
                        new
                        {
                            Id = 33,
                            Text = "In \"Gravity Falls\", how much does Waddles weigh when Mable wins him in \"The Time Traveler's Pig\"?"
                        },
                        new
                        {
                            Id = 34,
                            Text = "Which of the following songs did Elton John perform following Princess Diane's passing?"
                        },
                        new
                        {
                            Id = 35,
                            Text = "How many controllers could a Nintendo GameCube have plugged in at one time?"
                        },
                        new
                        {
                            Id = 36,
                            Text = "What is the name of the ship which was only a few miles away from the RMS Titanic when it struck an iceberg on April 14, 1912?"
                        },
                        new
                        {
                            Id = 37,
                            Text = "In \"Magic: The Gathering\", what instant card has the highest converted mana cost?"
                        },
                        new
                        {
                            Id = 38,
                            Text = "Which of the following won the first season of American Idol in 2002?"
                        },
                        new
                        {
                            Id = 39,
                            Text = "What is Lilo's last name from Lilo and Stitch?"
                        },
                        new
                        {
                            Id = 40,
                            Text = "Approximately how long is a year on Uranus?"
                        },
                        new
                        {
                            Id = 41,
                            Text = "Which NBA player won Most Valuable Player for the 1999-2000 season?"
                        },
                        new
                        {
                            Id = 42,
                            Text = "In which English county is the city of Portsmouth?"
                        },
                        new
                        {
                            Id = 43,
                            Text = "Which novel by John Grisham was conceived on a road trip to Florida while thinking about stolen books with his wife?"
                        },
                        new
                        {
                            Id = 44,
                            Text = "Which former US president used \"Let's Make America Great Again\" as his campaign slogan before Donald Trump's campaign?"
                        },
                        new
                        {
                            Id = 45,
                            Text = "In Game of Thrones what is the name of Jon Snow's sword?"
                        },
                        new
                        {
                            Id = 46,
                            Text = "How many states are in Australia?"
                        },
                        new
                        {
                            Id = 47,
                            Text = "What ability does Princess Sofia the First have from her amulet that allows her to breathe underwater?"
                        },
                        new
                        {
                            Id = 48,
                            Text = "Which of these is NOT a real tectonic plate?"
                        },
                        new
                        {
                            Id = 49,
                            Text = "In 2014, this new top 100 rapper who featured in \"Computers\" and \"Body Dance\" was arrested in a NYPD sting for murder."
                        },
                        new
                        {
                            Id = 50,
                            Text = "What does the computer software acronym JVM stand for?"
                        });
                });

            modelBuilder.Entity("Quizzer.Models.ScoreEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("QuizPlayerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuizPlayerId");

                    b.ToTable("ScoreEntries");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Quizzer.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Quizzer.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Quizzer.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Quizzer.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Quizzer.Models.Option", b =>
                {
                    b.HasOne("Quizzer.Models.Question", null)
                        .WithMany("Options")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Quizzer.Models.ScoreEntry", b =>
                {
                    b.HasOne("Quizzer.Models.ApplicationUser", "QuizPlayer")
                        .WithMany("ScoreEntries")
                        .HasForeignKey("QuizPlayerId");
                });
#pragma warning restore 612, 618
        }
    }
}
