// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Quizzer.Data;

namespace Quizzer.Data.Migrations
{
    [DbContext(typeof(QuizDbContext))]
    [Migration("20200607120922_initialcreate")]
    partial class initialcreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("IdentityServer4.EntityFramework.Entities.DeviceFlowCodes", b =>
                {
                    b.Property<string>("UserCode")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasMaxLength(50000);

                    b.Property<string>("DeviceCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<DateTime?>("Expiration")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("SubjectId")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.HasKey("UserCode");

                    b.HasIndex("DeviceCode")
                        .IsUnique();

                    b.HasIndex("Expiration");

                    b.ToTable("DeviceCodes");
                });

            modelBuilder.Entity("IdentityServer4.EntityFramework.Entities.PersistedGrant", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasMaxLength(50000);

                    b.Property<DateTime?>("Expiration")
                        .HasColumnType("datetime2");

                    b.Property<string>("SubjectId")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Key");

                    b.HasIndex("Expiration");

                    b.HasIndex("SubjectId", "ClientId", "Type");

                    b.ToTable("PersistedGrants");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Quizzer.Models.Answer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("Answers");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            IsCorrect = true,
                            QuestionId = 1,
                            Text = "October 29, 2003"
                        },
                        new
                        {
                            Id = 3,
                            IsCorrect = false,
                            QuestionId = 1,
                            Text = "December 1, 2003"
                        },
                        new
                        {
                            Id = 4,
                            IsCorrect = false,
                            QuestionId = 1,
                            Text = "November 14, 2002"
                        },
                        new
                        {
                            Id = 5,
                            IsCorrect = false,
                            QuestionId = 1,
                            Text = "July 18, 2004"
                        },
                        new
                        {
                            Id = 6,
                            IsCorrect = true,
                            QuestionId = 5,
                            Text = "Ed Sheeran - I See Fire"
                        },
                        new
                        {
                            Id = 7,
                            IsCorrect = false,
                            QuestionId = 5,
                            Text = "Marvin Gaye - Sexual Healing"
                        },
                        new
                        {
                            Id = 8,
                            IsCorrect = false,
                            QuestionId = 5,
                            Text = "Coldplay - Midnight"
                        },
                        new
                        {
                            Id = 9,
                            IsCorrect = false,
                            QuestionId = 5,
                            Text = "a-ha - Take On Me"
                        },
                        new
                        {
                            Id = 10,
                            IsCorrect = true,
                            QuestionId = 9,
                            Text = "Madeon"
                        },
                        new
                        {
                            Id = 11,
                            IsCorrect = false,
                            QuestionId = 9,
                            Text = "Daft Punk "
                        },
                        new
                        {
                            Id = 12,
                            IsCorrect = false,
                            QuestionId = 9,
                            Text = "Disclosure"
                        },
                        new
                        {
                            Id = 13,
                            IsCorrect = false,
                            QuestionId = 9,
                            Text = "David Guetta"
                        },
                        new
                        {
                            Id = 14,
                            IsCorrect = true,
                            QuestionId = 13,
                            Text = "Albus Percival Wulfric Brian Dumbledore"
                        },
                        new
                        {
                            Id = 15,
                            IsCorrect = false,
                            QuestionId = 13,
                            Text = "Albus Valum Jetta Mobius Dumbledore"
                        },
                        new
                        {
                            Id = 16,
                            IsCorrect = false,
                            QuestionId = 13,
                            Text = "Albus James Lunae Otto Dumbledore"
                        },
                        new
                        {
                            Id = 17,
                            IsCorrect = false,
                            QuestionId = 13,
                            Text = "Albus Valencium Horatio Kul Dumbledore"
                        },
                        new
                        {
                            Id = 18,
                            IsCorrect = true,
                            QuestionId = 17,
                            Text = "Germany"
                        },
                        new
                        {
                            Id = 19,
                            IsCorrect = false,
                            QuestionId = 17,
                            Text = "United Kingdom"
                        },
                        new
                        {
                            Id = 20,
                            IsCorrect = false,
                            QuestionId = 17,
                            Text = "Brazil"
                        },
                        new
                        {
                            Id = 21,
                            IsCorrect = false,
                            QuestionId = 17,
                            Text = "South Africa"
                        },
                        new
                        {
                            Id = 22,
                            IsCorrect = true,
                            QuestionId = 21,
                            Text = "Switzerland"
                        },
                        new
                        {
                            Id = 23,
                            IsCorrect = false,
                            QuestionId = 21,
                            Text = "United Kingdom"
                        },
                        new
                        {
                            Id = 24,
                            IsCorrect = false,
                            QuestionId = 21,
                            Text = "France"
                        },
                        new
                        {
                            Id = 25,
                            IsCorrect = false,
                            QuestionId = 21,
                            Text = "Belgium"
                        },
                        new
                        {
                            Id = 26,
                            IsCorrect = true,
                            QuestionId = 25,
                            Text = "1415"
                        },
                        new
                        {
                            Id = 27,
                            IsCorrect = false,
                            QuestionId = 25,
                            Text = "1463"
                        },
                        new
                        {
                            Id = 28,
                            IsCorrect = false,
                            QuestionId = 25,
                            Text = "1401"
                        },
                        new
                        {
                            Id = 29,
                            IsCorrect = false,
                            QuestionId = 25,
                            Text = "1422"
                        },
                        new
                        {
                            Id = 30,
                            IsCorrect = true,
                            QuestionId = 29,
                            Text = "Zepheniah Mann"
                        },
                        new
                        {
                            Id = 31,
                            IsCorrect = false,
                            QuestionId = 29,
                            Text = "Cave Johnson"
                        },
                        new
                        {
                            Id = 32,
                            IsCorrect = false,
                            QuestionId = 29,
                            Text = "Wallace Breem"
                        },
                        new
                        {
                            Id = 33,
                            IsCorrect = false,
                            QuestionId = 29,
                            Text = "Saxton Hale"
                        },
                        new
                        {
                            Id = 34,
                            IsCorrect = true,
                            QuestionId = 33,
                            Text = "The Shining"
                        },
                        new
                        {
                            Id = 35,
                            IsCorrect = false,
                            QuestionId = 33,
                            Text = "2001: A Space Odyssey"
                        },
                        new
                        {
                            Id = 36,
                            IsCorrect = false,
                            QuestionId = 33,
                            Text = " Dr. Strangelove "
                        },
                        new
                        {
                            Id = 37,
                            IsCorrect = false,
                            QuestionId = 33,
                            Text = "Eyes Wide Shut"
                        },
                        new
                        {
                            Id = 38,
                            IsCorrect = true,
                            QuestionId = 37,
                            Text = "September 19th"
                        },
                        new
                        {
                            Id = 39,
                            IsCorrect = false,
                            QuestionId = 37,
                            Text = "September 21st"
                        },
                        new
                        {
                            Id = 40,
                            IsCorrect = false,
                            QuestionId = 37,
                            Text = "September 30th"
                        },
                        new
                        {
                            Id = 41,
                            IsCorrect = false,
                            QuestionId = 37,
                            Text = "September 14th"
                        },
                        new
                        {
                            Id = 42,
                            IsCorrect = true,
                            QuestionId = 41,
                            Text = "Skies on Fire - AC/DC"
                        },
                        new
                        {
                            Id = 43,
                            IsCorrect = false,
                            QuestionId = 41,
                            Text = "Heathens - Twenty One Pilots"
                        },
                        new
                        {
                            Id = 44,
                            IsCorrect = false,
                            QuestionId = 41,
                            Text = "Without Me - Eminem"
                        },
                        new
                        {
                            Id = 45,
                            IsCorrect = false,
                            QuestionId = 41,
                            Text = "Fortunate Son - Creedence Clearwater Revival"
                        },
                        new
                        {
                            Id = 46,
                            IsCorrect = true,
                            QuestionId = 45,
                            Text = "Equatorial Guinea"
                        },
                        new
                        {
                            Id = 47,
                            IsCorrect = false,
                            QuestionId = 45,
                            Text = "Guinea"
                        },
                        new
                        {
                            Id = 48,
                            IsCorrect = false,
                            QuestionId = 45,
                            Text = "Cameroon"
                        },
                        new
                        {
                            Id = 49,
                            IsCorrect = false,
                            QuestionId = 45,
                            Text = "Angola"
                        },
                        new
                        {
                            Id = 50,
                            IsCorrect = true,
                            QuestionId = 49,
                            Text = "Interplay Entertainment "
                        },
                        new
                        {
                            Id = 51,
                            IsCorrect = false,
                            QuestionId = 49,
                            Text = "Capcom"
                        },
                        new
                        {
                            Id = 52,
                            IsCorrect = false,
                            QuestionId = 49,
                            Text = "Blizzard Entertainment"
                        },
                        new
                        {
                            Id = 53,
                            IsCorrect = false,
                            QuestionId = 49,
                            Text = "Nintendo"
                        },
                        new
                        {
                            Id = 54,
                            IsCorrect = true,
                            QuestionId = 53,
                            Text = "Tuba"
                        },
                        new
                        {
                            Id = 55,
                            IsCorrect = false,
                            QuestionId = 53,
                            Text = "Trombone"
                        },
                        new
                        {
                            Id = 56,
                            IsCorrect = false,
                            QuestionId = 53,
                            Text = "Contrabass"
                        },
                        new
                        {
                            Id = 57,
                            IsCorrect = false,
                            QuestionId = 53,
                            Text = "Bassoon"
                        },
                        new
                        {
                            Id = 58,
                            IsCorrect = true,
                            QuestionId = 57,
                            Text = "Vincent Vega"
                        },
                        new
                        {
                            Id = 59,
                            IsCorrect = false,
                            QuestionId = 57,
                            Text = "Jules Winnfield"
                        },
                        new
                        {
                            Id = 60,
                            IsCorrect = false,
                            QuestionId = 57,
                            Text = "Jimmie Dimmick"
                        },
                        new
                        {
                            Id = 61,
                            IsCorrect = false,
                            QuestionId = 57,
                            Text = "Butch Coolidge"
                        },
                        new
                        {
                            Id = 62,
                            IsCorrect = true,
                            QuestionId = 61,
                            Text = "Take off all your clothes"
                        },
                        new
                        {
                            Id = 63,
                            IsCorrect = false,
                            QuestionId = 61,
                            Text = "Take a cool shower"
                        },
                        new
                        {
                            Id = 64,
                            IsCorrect = false,
                            QuestionId = 61,
                            Text = "Drink some water"
                        },
                        new
                        {
                            Id = 65,
                            IsCorrect = false,
                            QuestionId = 61,
                            Text = "Go skinny dipping"
                        },
                        new
                        {
                            Id = 66,
                            IsCorrect = true,
                            QuestionId = 65,
                            Text = "Spooky Stuff"
                        },
                        new
                        {
                            Id = 67,
                            IsCorrect = false,
                            QuestionId = 65,
                            Text = "Ghosts n' Ghouls"
                        },
                        new
                        {
                            Id = 68,
                            IsCorrect = false,
                            QuestionId = 65,
                            Text = "Nerving Nights"
                        },
                        new
                        {
                            Id = 69,
                            IsCorrect = false,
                            QuestionId = 65,
                            Text = "Fearful Frights"
                        },
                        new
                        {
                            Id = 70,
                            IsCorrect = true,
                            QuestionId = 69,
                            Text = "Jens"
                        },
                        new
                        {
                            Id = 71,
                            IsCorrect = false,
                            QuestionId = 69,
                            Text = "Loki"
                        },
                        new
                        {
                            Id = 72,
                            IsCorrect = false,
                            QuestionId = 69,
                            Text = "Tyr"
                        },
                        new
                        {
                            Id = 73,
                            IsCorrect = false,
                            QuestionId = 69,
                            Text = "Snotra"
                        },
                        new
                        {
                            Id = 74,
                            IsCorrect = true,
                            QuestionId = 73,
                            Text = "Polska"
                        },
                        new
                        {
                            Id = 75,
                            IsCorrect = false,
                            QuestionId = 73,
                            Text = "Pupcia"
                        },
                        new
                        {
                            Id = 76,
                            IsCorrect = false,
                            QuestionId = 73,
                            Text = "Polszka"
                        },
                        new
                        {
                            Id = 77,
                            IsCorrect = false,
                            QuestionId = 73,
                            Text = "P&oacute;land"
                        },
                        new
                        {
                            Id = 78,
                            IsCorrect = true,
                            QuestionId = 77,
                            Text = "150"
                        },
                        new
                        {
                            Id = 79,
                            IsCorrect = false,
                            QuestionId = 77,
                            Text = "200"
                        },
                        new
                        {
                            Id = 80,
                            IsCorrect = false,
                            QuestionId = 77,
                            Text = "100"
                        },
                        new
                        {
                            Id = 81,
                            IsCorrect = false,
                            QuestionId = 77,
                            Text = "155"
                        },
                        new
                        {
                            Id = 82,
                            IsCorrect = true,
                            QuestionId = 81,
                            Text = "William Henry Harrison"
                        },
                        new
                        {
                            Id = 83,
                            IsCorrect = false,
                            QuestionId = 81,
                            Text = "Zachary Taylor"
                        },
                        new
                        {
                            Id = 84,
                            IsCorrect = false,
                            QuestionId = 81,
                            Text = "James A. Garfield"
                        },
                        new
                        {
                            Id = 85,
                            IsCorrect = false,
                            QuestionId = 81,
                            Text = "Warren G. Harding"
                        },
                        new
                        {
                            Id = 86,
                            IsCorrect = true,
                            QuestionId = 85,
                            Text = "Luminid"
                        },
                        new
                        {
                            Id = 87,
                            IsCorrect = false,
                            QuestionId = 85,
                            Text = "Dragalge"
                        },
                        new
                        {
                            Id = 88,
                            IsCorrect = false,
                            QuestionId = 85,
                            Text = "Mandibuzz"
                        },
                        new
                        {
                            Id = 89,
                            IsCorrect = false,
                            QuestionId = 85,
                            Text = "Araquanid"
                        },
                        new
                        {
                            Id = 90,
                            IsCorrect = true,
                            QuestionId = 89,
                            Text = "Serbia"
                        },
                        new
                        {
                            Id = 91,
                            IsCorrect = false,
                            QuestionId = 89,
                            Text = "Romania"
                        },
                        new
                        {
                            Id = 92,
                            IsCorrect = false,
                            QuestionId = 89,
                            Text = "Russia"
                        },
                        new
                        {
                            Id = 93,
                            IsCorrect = false,
                            QuestionId = 89,
                            Text = "Rwanda"
                        },
                        new
                        {
                            Id = 94,
                            IsCorrect = true,
                            QuestionId = 93,
                            Text = "Dan Smith"
                        },
                        new
                        {
                            Id = 95,
                            IsCorrect = false,
                            QuestionId = 93,
                            Text = "Will Farquarson"
                        },
                        new
                        {
                            Id = 96,
                            IsCorrect = false,
                            QuestionId = 93,
                            Text = "Kyle Simmons"
                        },
                        new
                        {
                            Id = 97,
                            IsCorrect = false,
                            QuestionId = 93,
                            Text = "Chris Wood"
                        },
                        new
                        {
                            Id = 98,
                            IsCorrect = true,
                            QuestionId = 97,
                            Text = "Kentucky Fried Chicken"
                        },
                        new
                        {
                            Id = 99,
                            IsCorrect = false,
                            QuestionId = 97,
                            Text = "Kentucky Fresh Cheese"
                        },
                        new
                        {
                            Id = 100,
                            IsCorrect = false,
                            QuestionId = 97,
                            Text = "Kibbled Freaky Cow"
                        },
                        new
                        {
                            Id = 101,
                            IsCorrect = false,
                            QuestionId = 97,
                            Text = "Kiwi Food Cut"
                        },
                        new
                        {
                            Id = 102,
                            IsCorrect = true,
                            QuestionId = 101,
                            Text = "685"
                        },
                        new
                        {
                            Id = 103,
                            IsCorrect = false,
                            QuestionId = 101,
                            Text = "1360"
                        },
                        new
                        {
                            Id = 104,
                            IsCorrect = false,
                            QuestionId = 101,
                            Text = "716"
                        },
                        new
                        {
                            Id = 105,
                            IsCorrect = false,
                            QuestionId = 101,
                            Text = "1155"
                        },
                        new
                        {
                            Id = 106,
                            IsCorrect = true,
                            QuestionId = 105,
                            Text = "Hamlet"
                        },
                        new
                        {
                            Id = 107,
                            IsCorrect = false,
                            QuestionId = 105,
                            Text = "The Tempest"
                        },
                        new
                        {
                            Id = 108,
                            IsCorrect = false,
                            QuestionId = 105,
                            Text = "Othello"
                        },
                        new
                        {
                            Id = 109,
                            IsCorrect = false,
                            QuestionId = 105,
                            Text = "The Taming of the Shrew"
                        },
                        new
                        {
                            Id = 110,
                            IsCorrect = true,
                            QuestionId = 109,
                            Text = "Answer a riddle"
                        },
                        new
                        {
                            Id = 111,
                            IsCorrect = false,
                            QuestionId = 109,
                            Text = "Rhythmically tap barrels with a wand"
                        },
                        new
                        {
                            Id = 112,
                            IsCorrect = false,
                            QuestionId = 109,
                            Text = "Speak a password"
                        },
                        new
                        {
                            Id = 113,
                            IsCorrect = false,
                            QuestionId = 109,
                            Text = "Knock in sequence"
                        },
                        new
                        {
                            Id = 114,
                            IsCorrect = true,
                            QuestionId = 113,
                            Text = "7"
                        },
                        new
                        {
                            Id = 115,
                            IsCorrect = false,
                            QuestionId = 113,
                            Text = "8"
                        },
                        new
                        {
                            Id = 116,
                            IsCorrect = false,
                            QuestionId = 113,
                            Text = "6"
                        },
                        new
                        {
                            Id = 117,
                            IsCorrect = false,
                            QuestionId = 113,
                            Text = "5"
                        },
                        new
                        {
                            Id = 118,
                            IsCorrect = true,
                            QuestionId = 117,
                            Text = "Lamborghini"
                        },
                        new
                        {
                            Id = 119,
                            IsCorrect = false,
                            QuestionId = 117,
                            Text = "Ferrari"
                        },
                        new
                        {
                            Id = 120,
                            IsCorrect = false,
                            QuestionId = 117,
                            Text = "Pagani"
                        },
                        new
                        {
                            Id = 121,
                            IsCorrect = false,
                            QuestionId = 117,
                            Text = "Bugatti"
                        },
                        new
                        {
                            Id = 122,
                            IsCorrect = true,
                            QuestionId = 121,
                            Text = "Ohio State Buckeyes"
                        },
                        new
                        {
                            Id = 123,
                            IsCorrect = false,
                            QuestionId = 121,
                            Text = "Alabama Crimson Tide"
                        },
                        new
                        {
                            Id = 124,
                            IsCorrect = false,
                            QuestionId = 121,
                            Text = "Clemson Tigers"
                        },
                        new
                        {
                            Id = 125,
                            IsCorrect = false,
                            QuestionId = 121,
                            Text = "Wisconsin Badgers"
                        },
                        new
                        {
                            Id = 126,
                            IsCorrect = true,
                            QuestionId = 125,
                            Text = "Russia"
                        },
                        new
                        {
                            Id = 127,
                            IsCorrect = false,
                            QuestionId = 125,
                            Text = "Canada"
                        },
                        new
                        {
                            Id = 128,
                            IsCorrect = false,
                            QuestionId = 125,
                            Text = "China"
                        },
                        new
                        {
                            Id = 129,
                            IsCorrect = false,
                            QuestionId = 125,
                            Text = "United States"
                        },
                        new
                        {
                            Id = 130,
                            IsCorrect = true,
                            QuestionId = 129,
                            Text = "The Director"
                        },
                        new
                        {
                            Id = 131,
                            IsCorrect = false,
                            QuestionId = 129,
                            Text = "Herbert P. Bear"
                        },
                        new
                        {
                            Id = 132,
                            IsCorrect = false,
                            QuestionId = 129,
                            Text = "Tusk"
                        },
                        new
                        {
                            Id = 133,
                            IsCorrect = false,
                            QuestionId = 129,
                            Text = "Ultimate Proto-Bot 10000"
                        },
                        new
                        {
                            Id = 134,
                            IsCorrect = true,
                            QuestionId = 133,
                            Text = "We Love to See You Smile"
                        },
                        new
                        {
                            Id = 135,
                            IsCorrect = false,
                            QuestionId = 133,
                            Text = "Why Pay More!?"
                        },
                        new
                        {
                            Id = 136,
                            IsCorrect = false,
                            QuestionId = 133,
                            Text = "Have It Your Way"
                        },
                        new
                        {
                            Id = 137,
                            IsCorrect = false,
                            QuestionId = 133,
                            Text = "Making People Happy Through Food"
                        },
                        new
                        {
                            Id = 138,
                            IsCorrect = true,
                            QuestionId = 137,
                            Text = "Clint Eastwood, Eli Wallach, and Lee Van Cleef"
                        },
                        new
                        {
                            Id = 139,
                            IsCorrect = false,
                            QuestionId = 137,
                            Text = "Sergio Leone, Ennio Morricone, and Tonino Delli Colli"
                        },
                        new
                        {
                            Id = 140,
                            IsCorrect = false,
                            QuestionId = 137,
                            Text = "Yul Brynner, Steve McQueen, and Charles Bronson"
                        },
                        new
                        {
                            Id = 141,
                            IsCorrect = false,
                            QuestionId = 137,
                            Text = "Aldo Giuffr&egrave;, Mario Brega, and Luigi Pistilli"
                        },
                        new
                        {
                            Id = 142,
                            IsCorrect = true,
                            QuestionId = 141,
                            Text = "Husker"
                        },
                        new
                        {
                            Id = 143,
                            IsCorrect = false,
                            QuestionId = 141,
                            Text = "Starbuck"
                        },
                        new
                        {
                            Id = 144,
                            IsCorrect = false,
                            QuestionId = 141,
                            Text = "Apollo"
                        },
                        new
                        {
                            Id = 145,
                            IsCorrect = false,
                            QuestionId = 141,
                            Text = "Crashdown"
                        },
                        new
                        {
                            Id = 146,
                            IsCorrect = true,
                            QuestionId = 145,
                            Text = "Scoot"
                        },
                        new
                        {
                            Id = 147,
                            IsCorrect = false,
                            QuestionId = 145,
                            Text = "Drake"
                        },
                        new
                        {
                            Id = 148,
                            IsCorrect = false,
                            QuestionId = 145,
                            Text = "Bill"
                        },
                        new
                        {
                            Id = 149,
                            IsCorrect = false,
                            QuestionId = 145,
                            Text = "Mallary"
                        },
                        new
                        {
                            Id = 150,
                            IsCorrect = true,
                            QuestionId = 149,
                            Text = "USS Hornet"
                        },
                        new
                        {
                            Id = 151,
                            IsCorrect = false,
                            QuestionId = 149,
                            Text = "USS Enterprise"
                        },
                        new
                        {
                            Id = 152,
                            IsCorrect = false,
                            QuestionId = 149,
                            Text = "USS Lexington"
                        },
                        new
                        {
                            Id = 153,
                            IsCorrect = false,
                            QuestionId = 149,
                            Text = "USS Saratoga"
                        },
                        new
                        {
                            Id = 154,
                            IsCorrect = true,
                            QuestionId = 153,
                            Text = "Google"
                        },
                        new
                        {
                            Id = 155,
                            IsCorrect = false,
                            QuestionId = 153,
                            Text = "Apple"
                        },
                        new
                        {
                            Id = 156,
                            IsCorrect = false,
                            QuestionId = 153,
                            Text = "Yahoo"
                        },
                        new
                        {
                            Id = 157,
                            IsCorrect = false,
                            QuestionId = 153,
                            Text = "Microsoft"
                        },
                        new
                        {
                            Id = 158,
                            IsCorrect = true,
                            QuestionId = 157,
                            Text = "7.62x39mm"
                        },
                        new
                        {
                            Id = 159,
                            IsCorrect = false,
                            QuestionId = 157,
                            Text = "7.62x51mm"
                        },
                        new
                        {
                            Id = 160,
                            IsCorrect = false,
                            QuestionId = 157,
                            Text = "5.56x45mm"
                        },
                        new
                        {
                            Id = 161,
                            IsCorrect = false,
                            QuestionId = 157,
                            Text = "5.45x39mm"
                        },
                        new
                        {
                            Id = 162,
                            IsCorrect = true,
                            QuestionId = 161,
                            Text = "Aqua"
                        },
                        new
                        {
                            Id = 163,
                            IsCorrect = false,
                            QuestionId = 161,
                            Text = "Vengaboys"
                        },
                        new
                        {
                            Id = 164,
                            IsCorrect = false,
                            QuestionId = 161,
                            Text = "Eiffel 65"
                        },
                        new
                        {
                            Id = 165,
                            IsCorrect = false,
                            QuestionId = 161,
                            Text = "Sash!"
                        },
                        new
                        {
                            Id = 166,
                            IsCorrect = true,
                            QuestionId = 165,
                            Text = "Titus Andronicus"
                        },
                        new
                        {
                            Id = 167,
                            IsCorrect = false,
                            QuestionId = 165,
                            Text = "Othello"
                        },
                        new
                        {
                            Id = 168,
                            IsCorrect = false,
                            QuestionId = 165,
                            Text = "Macbeth"
                        },
                        new
                        {
                            Id = 169,
                            IsCorrect = false,
                            QuestionId = 165,
                            Text = "King Lear"
                        },
                        new
                        {
                            Id = 170,
                            IsCorrect = true,
                            QuestionId = 169,
                            Text = "187"
                        },
                        new
                        {
                            Id = 171,
                            IsCorrect = false,
                            QuestionId = 169,
                            Text = "207"
                        },
                        new
                        {
                            Id = 172,
                            IsCorrect = false,
                            QuestionId = 169,
                            Text = "197"
                        },
                        new
                        {
                            Id = 173,
                            IsCorrect = false,
                            QuestionId = 169,
                            Text = "177"
                        },
                        new
                        {
                            Id = 174,
                            IsCorrect = true,
                            QuestionId = 173,
                            Text = "George H. W. Bush"
                        },
                        new
                        {
                            Id = 175,
                            IsCorrect = false,
                            QuestionId = 173,
                            Text = "Richard Nixon"
                        },
                        new
                        {
                            Id = 176,
                            IsCorrect = false,
                            QuestionId = 173,
                            Text = "George W. Bush "
                        },
                        new
                        {
                            Id = 177,
                            IsCorrect = false,
                            QuestionId = 173,
                            Text = "Ronald Regan"
                        },
                        new
                        {
                            Id = 178,
                            IsCorrect = true,
                            QuestionId = 177,
                            Text = "Skiing"
                        },
                        new
                        {
                            Id = 179,
                            IsCorrect = false,
                            QuestionId = 177,
                            Text = "Swimming"
                        },
                        new
                        {
                            Id = 180,
                            IsCorrect = false,
                            QuestionId = 177,
                            Text = "Showjumping"
                        },
                        new
                        {
                            Id = 181,
                            IsCorrect = false,
                            QuestionId = 177,
                            Text = "Gymnastics"
                        },
                        new
                        {
                            Id = 182,
                            IsCorrect = true,
                            QuestionId = 181,
                            Text = "For Emma, Forever Ago"
                        },
                        new
                        {
                            Id = 183,
                            IsCorrect = false,
                            QuestionId = 181,
                            Text = "Bon Iver, Bon Iver"
                        },
                        new
                        {
                            Id = 184,
                            IsCorrect = false,
                            QuestionId = 181,
                            Text = "22, A Million"
                        },
                        new
                        {
                            Id = 185,
                            IsCorrect = false,
                            QuestionId = 181,
                            Text = "Blood Bank EP"
                        },
                        new
                        {
                            Id = 186,
                            IsCorrect = true,
                            QuestionId = 185,
                            Text = "Utah Teapot"
                        },
                        new
                        {
                            Id = 187,
                            IsCorrect = false,
                            QuestionId = 185,
                            Text = "Pixar Teapot"
                        },
                        new
                        {
                            Id = 188,
                            IsCorrect = false,
                            QuestionId = 185,
                            Text = "3D Teapot"
                        },
                        new
                        {
                            Id = 189,
                            IsCorrect = false,
                            QuestionId = 185,
                            Text = "Tennessee Teapot"
                        },
                        new
                        {
                            Id = 190,
                            IsCorrect = true,
                            QuestionId = 189,
                            Text = "Marlon"
                        },
                        new
                        {
                            Id = 191,
                            IsCorrect = false,
                            QuestionId = 189,
                            Text = "Marnie"
                        },
                        new
                        {
                            Id = 192,
                            IsCorrect = false,
                            QuestionId = 189,
                            Text = "Morris"
                        },
                        new
                        {
                            Id = 193,
                            IsCorrect = false,
                            QuestionId = 189,
                            Text = "Marvin"
                        },
                        new
                        {
                            Id = 194,
                            IsCorrect = true,
                            QuestionId = 193,
                            Text = "October 31st, 2019"
                        },
                        new
                        {
                            Id = 195,
                            IsCorrect = false,
                            QuestionId = 193,
                            Text = "January 13th, 2019"
                        },
                        new
                        {
                            Id = 196,
                            IsCorrect = false,
                            QuestionId = 193,
                            Text = "September 6th, 2018"
                        },
                        new
                        {
                            Id = 197,
                            IsCorrect = false,
                            QuestionId = 193,
                            Text = "October 1st, 2019"
                        },
                        new
                        {
                            Id = 198,
                            IsCorrect = true,
                            QuestionId = 197,
                            Text = "Java Virtual Machine"
                        },
                        new
                        {
                            Id = 199,
                            IsCorrect = false,
                            QuestionId = 197,
                            Text = "Java Vendor Machine"
                        },
                        new
                        {
                            Id = 200,
                            IsCorrect = false,
                            QuestionId = 197,
                            Text = "Java Visual Machine"
                        },
                        new
                        {
                            Id = 201,
                            IsCorrect = false,
                            QuestionId = 197,
                            Text = "Just Virtual Machine"
                        });
                });

            modelBuilder.Entity("Quizzer.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Quizzer.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Text = "When was the first Call of Duty title released?"
                        },
                        new
                        {
                            Id = 5,
                            Text = "Electronic music producer Kygo's popularity skyrocketed after a certain remix. Which song did he remix?"
                        },
                        new
                        {
                            Id = 9,
                            Text = "What French artist/band is known for playing on the midi instrument \"Launchpad\"?"
                        },
                        new
                        {
                            Id = 13,
                            Text = "In the \"Harry Potter\" series, what is Headmaster Dumbledore's full name?"
                        },
                        new
                        {
                            Id = 17,
                            Text = "Which nation hosted the FIFA World Cup in 2006?"
                        },
                        new
                        {
                            Id = 21,
                            Text = "The World Health Organization headquarters is located in which European country?"
                        },
                        new
                        {
                            Id = 25,
                            Text = "What year did the Battle of Agincourt take place?"
                        },
                        new
                        {
                            Id = 29,
                            Text = "Who is the founder of Team Fortress 2's fictional company \"Mann Co\"?"
                        },
                        new
                        {
                            Id = 33,
                            Text = "Which movie of film director Stanley Kubrick is known to be an adaptation of a Stephen King novel?"
                        },
                        new
                        {
                            Id = 37,
                            Text = "Capcom's survival horror title Dead Rising, canonically starts on what day of September 2006?"
                        },
                        new
                        {
                            Id = 41,
                            Text = "Which of these songs is NOT included in the Suicide Squad OST?"
                        },
                        new
                        {
                            Id = 45,
                            Text = "Which of these African countries list \"Spanish\" as an official language?"
                        },
                        new
                        {
                            Id = 49,
                            Text = "Which company did Bethesda purchase the Fallout Series from?"
                        },
                        new
                        {
                            Id = 53,
                            Text = "In an orchestra, what is the lowest member of the brass family?"
                        },
                        new
                        {
                            Id = 57,
                            Text = "Who in Pulp Fiction says \"No, they got the metric system there, they wouldn't know what the fuck a Quarter Pounder is.\""
                        },
                        new
                        {
                            Id = 61,
                            Text = "According to the American rapper Nelly, what should you do when its hot in here?"
                        },
                        new
                        {
                            Id = 65,
                            Text = "What's the name of the halloween-related Sims 4 Stuff Pack released September 29th, 2015?"
                        },
                        new
                        {
                            Id = 69,
                            Text = "Which of the following is NOT a god in Norse Mythology."
                        },
                        new
                        {
                            Id = 73,
                            Text = "What is the name of Poland in Polish?"
                        },
                        new
                        {
                            Id = 77,
                            Text = "How many calories are in a 355 ml can of Pepsi Cola?"
                        },
                        new
                        {
                            Id = 81,
                            Text = "Which of the following United States Presidents served the shortest term in office?"
                        },
                        new
                        {
                            Id = 85,
                            Text = "Which of the following is not a real Pok&eacute;mon?"
                        },
                        new
                        {
                            Id = 89,
                            Text = ".rs is the top-level domain for what country?"
                        },
                        new
                        {
                            Id = 93,
                            Text = "Who is the lead singer of Bastille?"
                        },
                        new
                        {
                            Id = 97,
                            Text = "What do the letters of the fast food chain KFC stand for?"
                        },
                        new
                        {
                            Id = 101,
                            Text = "How many trophies are there in \"Super Smash Bros. for Nintendo 3DS\"?"
                        },
                        new
                        {
                            Id = 105,
                            Text = "\"Doctor Who\" star David Tennant performed in a rendition of which Shakespearean play?"
                        },
                        new
                        {
                            Id = 109,
                            Text = "In the \"Harry Potter\" novels, what must a Hogwarts student do to enter the Ravenclaw Common Room?"
                        },
                        new
                        {
                            Id = 113,
                            Text = "How many sides does a heptagon have?"
                        },
                        new
                        {
                            Id = 117,
                            Text = "Which car manufacturer created the \"Aventador\"?"
                        },
                        new
                        {
                            Id = 121,
                            Text = "Who won the 2015 College Football Playoff (CFP) National Championship? "
                        },
                        new
                        {
                            Id = 125,
                            Text = "What is the largest country in the world?"
                        },
                        new
                        {
                            Id = 129,
                            Text = "Which of these characters wasn't a villian in Club Penguin?"
                        },
                        new
                        {
                            Id = 133,
                            Text = "Which slogan did the fast food company, McDonald's, use before their \"I'm Lovin' It\" slogan?"
                        },
                        new
                        {
                            Id = 137,
                            Text = "Which actors made up the trio in \"The Good, the Bad, and the Ugly\"? "
                        },
                        new
                        {
                            Id = 141,
                            Text = "What was the callsign of Commander William Adama in Battlestar Galactica (2004)?"
                        },
                        new
                        {
                            Id = 145,
                            Text = "Which character in the \"Animal Crossing\" series uses the phrase \"zip zoom\" when talking to the player?"
                        },
                        new
                        {
                            Id = 149,
                            Text = "On which aircraft carrier did the Doolitte Raid launch from on April 18, 1942 during World War II?"
                        },
                        new
                        {
                            Id = 153,
                            Text = "Which company's original slogan was \"Don't be evil\"?"
                        },
                        new
                        {
                            Id = 157,
                            Text = "What round is a classic AK-47 chambered in?"
                        },
                        new
                        {
                            Id = 161,
                            Text = "\"Doctor Jones\", \"Turn Back Time\" and \"Barbie Girl\" were UK number ones for which Eurodance group?"
                        },
                        new
                        {
                            Id = 165,
                            Text = "Which Shakespeare play features the stage direction \"Enter a messenger, with two heads and a hand\"?"
                        },
                        new
                        {
                            Id = 169,
                            Text = "What is the sum of all the tiles in a standard box of Scrabble?"
                        },
                        new
                        {
                            Id = 173,
                            Text = "Which U.S. President was in office when the Gulf War began?"
                        },
                        new
                        {
                            Id = 177,
                            Text = "In what sport does Fanny Chmelar compete for Germany?"
                        },
                        new
                        {
                            Id = 181,
                            Text = "What was Bon Iver's debut album released in 2007?"
                        },
                        new
                        {
                            Id = 185,
                            Text = "The teapot often seen in many 3D modeling applications is called what?"
                        },
                        new
                        {
                            Id = 189,
                            Text = "What is the name of the adventurer you meet at the mines in Stardew Valley?"
                        },
                        new
                        {
                            Id = 193,
                            Text = "When was \"Luigi's Mansion 3\" released?"
                        },
                        new
                        {
                            Id = 197,
                            Text = "What does the computer software acronym JVM stand for?"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Quizzer.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Quizzer.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Quizzer.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Quizzer.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Quizzer.Models.Answer", b =>
                {
                    b.HasOne("Quizzer.Models.Question", null)
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Quizzer.Models.ApplicationUser", b =>
                {
                    b.OwnsMany("Quizzer.Models.ScoreEntry", "ScoreEntries", b1 =>
                        {
                            b1.Property<string>("QuizPlayerId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<int>("Score")
                                .HasColumnType("int");

                            b1.HasKey("QuizPlayerId", "Id");

                            b1.ToTable("ScoreEntries");

                            b1.WithOwner("QuizPlayer")
                                .HasForeignKey("QuizPlayerId");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
